
#include "..\Includes\Editor.h"
#include "..\Includes\Texts.h"

/*** Menus **************************************************************/

FLAGARRAY		DisplayFlags[]={{IDM_FLAGTERRAIN,   MVF_TERRAIN},
					{IDM_FLAGCREATURES, MVF_CREATURES},
					{IDM_FLAGDOORS,     MVF_DOORS},
					{IDM_FLAGTRAPS,     MVF_TRAPS},
					{IDM_FLAGMAGICALS,  MVF_MAGICALOBJECTS},
					{IDM_FLAGOBJECTS,   MVF_OBJECTS},
					{IDM_FLAGGATES,     MVF_GATES},
					{IDM_FLAGAREAS,     MVF_AREAS},
					{IDM_FLAGPATHS,     MVF_PATHS},
					{IDM_FLAGEFFECTS,   MVF_EFFECTS},
					{IDM_FLAGCAMERAS,   MVF_CAMERAS},
                                        {IDM_MOREDETAILS,   MVF_DETAILED},
					{IDM_EXPANDGATES,   MVF_EXPANDGATES},
					{IDM_OBJECTSCOLOR,  MVF_OBJECTUSESPLYCOL},
					{IDM_MAGICSCOLOR,   MVF_MAGICUSESPLYCOL},
					{0,		    0}};

CUSTOMITEM 		MainMenu[]={	// Menu Fichier
					{TRUE,  IDM_NEW,			60, NULL, NULL, szMainMenuNew,				0, szMainMenuKeyNew, 0},
					{TRUE,  IDM_DISK,			00, NULL, NULL, szMainMenuDisk,				0, NULL, 4},
					{TRUE,  IDM_OPEN,			61, NULL, NULL, szMainMenuOpen,				0, szMainMenuKeyOpen, 0},
					{TRUE,  IDM_RECENT,			00, NULL, NULL, szMainMenuRecent,				0, NULL, 0},
					{TRUE,  IDM_SAVE,			62, NULL, NULL, szMainMenuSave,				0, szMainMenuKeySave, 0},
					{TRUE,  IDM_SAVEAS,			00, NULL, NULL, szMainMenuSaveAs,				0, NULL, 0},
					{TRUE,  IDM_COMPILATION,		00, NULL, NULL, szMainMenuCompilation,			0, NULL, 4},
					{TRUE,  IDM_COMPILE,			73, NULL, NULL, szMainMenuCompile,			0, szMainMenuKeyCompile, 0},
					{TRUE,  IDM_TEST,			00, NULL, NULL, szMainMenuTest,				0, szMainMenuKeyTest, 0},
					{TRUE,  IDM_EXECUTE,			74, NULL, NULL, szMainMenuExecute,			0, szMainMenuKeyExecute, 0},
					{TRUE,  IDM_QUIT,			00, NULL, NULL, szMainMenuQuit,				0, NULL, 0},
					// Menu Edition
					{TRUE,  IDM_UNDO,			00, NULL, NULL, szMainMenuUndo,				0, NULL, 4},// Undo
					{TRUE,  IDM_UNDOLAST,			65, NULL, NULL, szMainMenuUndoLast,			0, szMainMenuKeyUndoLast, 0},
					{TRUE,  IDM_UNDOMNU,			00, NULL, NULL, szMainMenuUndoMnu,			0, NULL, 0},
					{TRUE,  IDM_UNDOHISTORY,		00, NULL, NULL, szMainMenuUndoHistory,			0, NULL, 0},
					{TRUE,  IDM_UNDOFREE,			00, NULL, NULL, szMainMenuUndoFree,			0, NULL, 0},
					{TRUE,  IDM_UNDOCOUNT,			00, NULL, NULL, szMainMenuUndoCount,			0, NULL, 0},
					{TRUE,  IDM_SELRECT,			00, NULL, NULL, szMainMenuSelRect,			0, NULL, 4},// EditBox
					{TRUE,  IDM_COPY,			63, NULL, NULL, szMainMenuCopy,				0, szMainMenuKeyCopy, 0},
					{TRUE,  IDM_CUT,			71, NULL, NULL, szMainMenuCut,				0, szMainMenuKeyCut, 0},
					{TRUE,  IDM_PASTE,			64, NULL, NULL, szMainMenuPaste,				0, szMainMenuKeyPaste, 0},
					{TRUE,  IDM_LOADBRUSH,			00, NULL, NULL, szMainMenuLoadBrush,			0, NULL, 0},
					{TRUE,  IDM_LOADBRUSHINSEL,		00, NULL, NULL, szMainMenuLoadBrushInSel,		0, NULL, 0},
					{TRUE,  IDM_LOADBRUSHINCOPY,		00, NULL, NULL, szMainMenuLoadBrushInCopy,		0, NULL, 0},
					{TRUE,  IDM_SAVEBRUSH,			00, NULL, NULL, szMainMenuSaveBrush,			0, NULL, 0},
					{TRUE,  IDM_SELECTION,			00, NULL, NULL, szMainMenuSelection,			0, NULL, 0},
					{TRUE,  IDM_COPYZONE,			00, NULL, NULL, szMainMenuCopyZone,			0, NULL, 0},
					{TRUE,  IDM_TRANSFORM,			00, NULL, NULL, szMainMenuTransform,			0, NULL, 0},
					{TRUE,  IDM_ROTATEP90,			00, NULL, NULL, szMainMenuRotateP90,			0, szMainMenuKeyRotateP90, 0},
					{TRUE,  IDM_ROTATEM90,			00, NULL, NULL, szMainMenuRotateM90,			0, szMainMenuKeyRotateM90, 0},
					{TRUE,  IDM_SYMHORZ,			00, NULL, NULL, szMainMenuSymHorz,			0, szMainMenuKeySymHorz, 0},
					{TRUE,  IDM_SYMVERT,			00, NULL, NULL, szMainMenuSymVert,			0, szMainMenuKeySymVert, 0},
					{TRUE,  IDM_SELECTCHANGE,		00, NULL, NULL, szMainMenuSelectChange,			0, NULL, 0},
					{TRUE,  IDM_SELECTALL,			00, NULL, NULL, szMainMenuSelectAll,			0, szMainMenuKeySelectAll, 0},
					{TRUE,  IDM_SELECTNONE,			00, NULL, NULL, szMainMenuSelectNone,			0, szMainMenuKeySelectNone, 0},
					{TRUE,	IDM_SEARCH,			00, NULL, NULL, szMainMenuSearch,				0, NULL, 4},// Research
					{TRUE,	IDM_FIND,			76, NULL, NULL, szMainMenuFind,				0, szMainMenuKeyFind, 0},
					{TRUE,  IDM_WORLDELEMENTS,		00, NULL, NULL, szMainMenuWorldElem,			0, NULL, 4},// WrldEl
					{TRUE,  IDM_CREATURES,			68, NULL, NULL, szMainMenuCreatures,			0, NULL, 0},
					{TRUE,  IDM_DOORSTRAPS,			69, NULL, NULL, szMainMenuDoorsTraps,			0, NULL, 0},
					{TRUE,  IDM_OBJECTS,			70, NULL, NULL, szMainMenuObjects,			0, NULL, 0},
					{TRUE,  IDM_OTHERS,			00, NULL, NULL, szMainMenuOthers,				0, NULL, 4},// Others
					{TRUE,  IDM_HEROS,			00, NULL, NULL, szMainMenuHeros,				0, NULL, 0},
					{TRUE,  IDM_AREAS,			00, NULL, NULL, szMainMenuAreas,				0, NULL, 0},
					{TRUE,  IDM_GATES,			00, NULL, NULL, szMainMenuGates,				0, NULL, 0},
					{TRUE,	IDM_PATHS,			00, NULL, NULL, szMainMenuPaths,				0, NULL, 0},
					{TRUE,	IDM_EFFECTS,			00, NULL, NULL, szMainMenuEffects,			0, NULL, 0},
					{TRUE,  IDM_EVENTS,			00, NULL, NULL, szMainMenuEvents,				0, NULL, 0},
					{TRUE,	IDM_CREATURESPROPERTIES,	00, NULL, NULL, szMainMenuCreaturesProperties,	0, NULL, 0},
					{TRUE,  IDM_GAMEPROPERTIES,		00, NULL, NULL, szMainMenuGameProperties,		0, NULL, 0},// Game
					{TRUE,  IDM_MAPPROPERTIES,		00, NULL, NULL, szMainMenuMapProperties,		0, NULL, 0},
					// Menu Dessin
					{TRUE,  IDM_PAINTBRUSH,			00, NULL, NULL, szMainMenuPaintBrush,			0, NULL, 4},// PaintBrush
					{TRUE,  IDM_WORLDELEM,			00, NULL, NULL, szMainMenuWorldElem,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDLIMIT,		00, NULL, NULL, szMapWorldLimit,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDWATER,		00, NULL, NULL, szMapWorldWater,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDLAVA,		00, NULL, NULL, szMapWorldLava,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDGOLD,		00, NULL, NULL, szMapWorldGold,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDGEMS,		00, NULL, NULL, szMapWorldGems,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDSOLID,		00, NULL, NULL, szMapWorldSolid,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDROCK,		00, NULL, NULL, szMapWorldRock,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDUNCLAIMED,		00, NULL, NULL, szMapWorldUnclaimed,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDHEROREST,		00, NULL, NULL, szMapWorldHeroRest,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDMANACLOSED,		00, NULL, NULL, szMapWorldManaClosed,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDHEROPORTALS,	00, NULL, NULL, szMainMenuHeroPortals,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDHEROSGATE1,		00, NULL, NULL, szMapWorldHerosGate1,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDHEROSGATE2,		00, NULL, NULL, szMapWorldHerosGate2,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDHEROSGATE3,		00, NULL, NULL, szMapWorldHerosGate3,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDHEROSGATE4,		00, NULL, NULL, szMapWorldHerosGate4,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDHEROSGATE6,		00, NULL, NULL, szMapWorldHerosGate6,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDHEROSGATE7,		00, NULL, NULL, szMapWorldHerosGate7,			0, NULL, 1},
					{TRUE,  IDM_ROOMS,			00, NULL, NULL, szMainMenuRooms,				0, NULL, 1},
					{TRUE,  IDM_PLAYERS,			00, NULL, NULL, szMainMenuPlayers,			0, NULL, 0},
					{TRUE,  IDM_PLAYERS1,			00, NULL, NULL, szMenuPlayers01,				0, NULL, 1},
					{TRUE,  IDM_PLAYERS2,			00, NULL, NULL, szMenuPlayers02,				0, NULL, 1},
					{TRUE,  IDM_PLAYERS3,			00, NULL, NULL, szMenuPlayers03,				0, NULL, 1},
					{TRUE,  IDM_PLAYERS4,			00, NULL, NULL, szMenuPlayers04,				0, NULL, 1},
					{TRUE,  IDM_PLAYERS5,			00, NULL, NULL, szMenuPlayers05,				0, NULL, 1},
					{TRUE,  IDM_PLAYERS6,			00, NULL, NULL, szMenuPlayers06,				0, NULL, 1},
					{TRUE,  IDM_PLAYERS7,			00, NULL, NULL, szMenuPlayers07,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDWALL,		00, NULL, NULL, szMapWorldWall,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDCLAIMED,		00, NULL, NULL, szMapWorldClaimed,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDHEART,		00, NULL, NULL, szMapWorldHeart,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDLAIR,		00, NULL, NULL, szMapWorldLair,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDLIBRARY,		00, NULL, NULL, szMapWorldLibrary,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDTREASURY,		00, NULL, NULL, szMapWorldTreasury,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDCASINO,		00, NULL, NULL, szMapWorldCasino,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDWOODENBRIDGEWATER,	00, NULL, NULL, szMapWorldWoodenBridgeUnderWater,	0, NULL, 1},
					{TRUE,  IDM_MAPWORLDWOODENBRIDGELAVA,	00, NULL, NULL, szMapWorldWoodenBridgeUnderLava,	0, NULL, 1},
					{TRUE,  IDM_MAPWORLDTORTURE,		00, NULL, NULL, szMapWorldTorture,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDGRAVEYARD,		00, NULL, NULL, szMapWorldGraveYard,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDTEMPLE,		00, NULL, NULL, szMapWorldTemple,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDHEROSBRIDGEWATER,	00, NULL, NULL, szMapWorldHerosBridgeUnderWater,	0, NULL, 1},
					{TRUE,  IDM_MAPWORLDHEROSBRIDGELAVA,	00, NULL, NULL, szMapWorldHerosBridgeUnderLava,	0, NULL, 1},
					{TRUE,  IDM_MAPWORLDMERCENARIES,	00, NULL, NULL, szMapWorldMercenariesPortal,		0, NULL, 1},
					{TRUE,  IDM_MAPWORLDPORTAL,		00, NULL, NULL, szMapWorldPortal,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDHATCHERY,		00, NULL, NULL, szMapWorldHatchery,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDTRAINING,		00, NULL, NULL, szMapWorldTraining,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDWORKSHOP,		00, NULL, NULL, szMapWorldWorkShop,			0, NULL, 1},
					{TRUE,  IDM_MAPWORLDGUARD,		00, NULL, NULL, szMapWorldGuard,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDPRISON,		00, NULL, NULL, szMapWorldPrison,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDSTONEBRIDGEWATER,	00, NULL, NULL, szMapWorldStoneBridgeUnderWater,	0, NULL, 1},
					{TRUE,  IDM_MAPWORLDSTONEBRIDGELAVA,	00, NULL, NULL, szMapWorldStoneBridgeUnderLava,	0, NULL, 1},
					{TRUE,  IDM_MAPWORLDPIT,		00, NULL, NULL, szMapWorldPit,				0, NULL, 1},
					{TRUE,  IDM_MAPWORLDMANAOPENED,		00, NULL, NULL, szMapWorldManaOpened,			0, NULL, 1},
					{TRUE,  IDM_PAINTMODE,			00, NULL, NULL, szMainMenuPaintMode,			0, NULL, 4},// PaintMde
					{TRUE,  IDM_RECT,			00, NULL, NULL, szMainMenuRect,				0, szMainMenuKeyRect, 1},
					{TRUE,  IDM_RECTFILL,			00, NULL, NULL, szMainMenuRectFill,			0, szMainMenuKeyRectFill, 1},
					{TRUE,  IDM_CIRCLE,			00, NULL, NULL, szMainMenuCircle,				0, szMainMenuKeyCircle, 1},
					{TRUE,  IDM_CIRCLEFILL,			00, NULL, NULL, szMainMenuCircleFill,			0, szMainMenuKeyCircleFill, 1},
					{TRUE,  IDM_LINE,			00, NULL, NULL, szMainMenuLine,				0, szMainMenuKeyLine, 1},
					{TRUE,  IDM_PEN,			00, NULL, NULL, szMainMenuPen,				0, szMainMenuKeyPen, 1},
					{TRUE,  IDM_FILL,			00, NULL, NULL, szMainMenuFill,				0, szMainMenuKeyFill, 1},
					{TRUE,  IDM_PUTELEM,			00, NULL, NULL, szMainMenuPutElem,			0, NULL, 1},
					{TRUE,  IDM_PUTCREATURE,		00, NULL, NULL, szMainMenuPutCreature,			0, szMainMenuKeyPutCreature, 1},
					{TRUE,  IDM_PUTDOOR,			00, NULL, NULL, szMainMenuPutDoor,			0, szMainMenuKeyPutDoor, 1},
					{TRUE,  IDM_PUTTRAP,			00, NULL, NULL, szMainMenuPutTrap,			0, szMainMenuKeyPutTrap, 1},
					{TRUE,  IDM_PUTOBJECT,			00, NULL, NULL, szMainMenuPutObject,			0, szMainMenuKeyPutObject, 1},
					{TRUE,  IDM_PUTMAGICALOBJECT,		00, NULL, NULL, szMainMenuPutMagicalObject,		0, szMainMenuKeyPutMagicalObject, 1},
					{TRUE,  IDM_MODIFYCREATURE,		00, NULL, NULL, szMainMenuModifyCreature,		0, NULL, 0},
					{TRUE,  IDM_MODIFYDOOR,			00, NULL, NULL, szMainMenuModifyDoor,			0, NULL, 0},
					{TRUE,  IDM_MODIFYTRAP,			00, NULL, NULL, szMainMenuModifyTrap,			0, NULL, 0},
					{TRUE,  IDM_MODIFYOBJECT,		00, NULL, NULL, szMainMenuModifyObject,			0, NULL, 0},
					{TRUE,  IDM_MODIFYMAGICALOBJECT,	00, NULL, NULL, szMainMenuModifyMagicalObject,	0, NULL, 0},
					// Menu Afficher
					{TRUE,  IDM_WINDOWS,			00, NULL, NULL, szMainMenuWindows,			0, NULL, 4},
					{TRUE,  IDM_THUMBNAIL,			67, NULL, NULL, szMainMenuThumbnail,			0, NULL, 0},
					{TRUE,  IDM_FULLSCREEN,			00, NULL, NULL, szMainMenuFullScreen,			0, NULL, 0},
					{TRUE,  IDM_MAPSTATS,			00, NULL, NULL, szMainMenuMapStats,			0, NULL, 0},
					{TRUE,  IDM_TOOLBAR,			00, NULL, NULL, szMainMenuToolbar,			0, NULL, 1},
					{TRUE,  IDM_MINIMAP,			00, NULL, NULL, szMainMenuMinimap,			0, NULL, 1},
					{TRUE,  IDM_MINIMAPPARAMS,		00, NULL, NULL, szMainMenuMinimapParams,		0, NULL, 0},
					{TRUE,  IDM_KEEPPROPS,			00, NULL, NULL, szMainMenuKeepProps,			0, NULL, 1},
					{TRUE,  IDM_MAP,			00, NULL, NULL, szMainMenuMap,				0, NULL, 4},
					{TRUE,  IDM_DISPLAYCREATURES,		00, NULL, NULL, szMainMenuDisplayCreatures,		0, NULL, 1},
					{TRUE,  IDM_DISPLAYDOORS,		00, NULL, NULL, szMainMenuDisplayDoors,			0, NULL, 1},
					{TRUE,  IDM_DISPLAYTRAPS,		00, NULL, NULL, szMainMenuDisplayTraps,			0, NULL, 1},
					{TRUE,  IDM_DISPLAYMAGICS,		00, NULL, NULL, szMainMenuDisplayMagics,		0, NULL, 1},
					{TRUE,  IDM_FLAGTERRAIN,		00, NULL, NULL, szMainMenuFlagTerrain,			0, NULL, 1},
					{TRUE,  IDM_FLAGCREATURES,		00, NULL, NULL, szMainMenuFlagCreatures,		0, NULL, 1},
					{TRUE,  IDM_FLAGDOORS,			00, NULL, NULL, szMainMenuFlagDoors,			0, NULL, 1},
					{TRUE,  IDM_FLAGTRAPS,			00, NULL, NULL, szMainMenuFlagTraps,			0, NULL, 1},
					{TRUE,  IDM_FLAGMAGICALS,		00, NULL, NULL, szMainMenuFlagMagicals,			0, NULL, 1},
					{TRUE,  IDM_FLAGOBJECTS,		00, NULL, NULL, szMainMenuFlagObjects,			0, NULL, 1},
					{TRUE,  IDM_FLAGAREAS,			00, NULL, NULL, szMainMenuFlagAreas,			0, NULL, 1},
					{TRUE,  IDM_FLAGPATHS,			00, NULL, NULL, szMainMenuFlagPaths,			0, NULL, 1},
					{TRUE,  IDM_FLAGGATES,			00, NULL, NULL, szMainMenuFlagGates,			0, NULL, 1},
					{TRUE,  IDM_FLAGEFFECTS,		00, NULL, NULL, szMainMenuFlagEffects,			0, NULL, 1},
					{TRUE,  IDM_FLAGCAMERAS,		00, NULL, NULL, szMainMenuFlagCameras,			0, NULL, 1},
					{TRUE,  IDM_OPTIONS,			00, NULL, NULL, szMainMenuOptions,			0, NULL, 4},
					{TRUE,  IDM_MOREDETAILS,		00, NULL, NULL, szMainMenuMoreDetails,			0, NULL, 1},
					{TRUE,  IDM_EXPANDGATES,		00, NULL, NULL, szMainMenuExpandGates,			0, NULL, 1},
					{TRUE,  IDM_OBJECTSCOLOR,		00, NULL, NULL, szMainMenuObjectsColor,			0, NULL, 1},
					{TRUE,  IDM_MAGICSCOLOR,		00, NULL, NULL, szMainMenuMagicsColor,			0, NULL, 1},
					// Menu Propriétés
					{TRUE,  IDM_PROPERTIES,			72, NULL, NULL, szMainMenuProperties,			0, NULL, 0},
					{TRUE,  IDM_PROPERTIESSAVE,		00, NULL, NULL, szMainMenuPropertiesSave,		0, NULL, 1},
					{TRUE,  IDM_PROPERTIESSAVENOW,		00, NULL, NULL, szMainMenuPropertiesSaveNow,		0, NULL, 0},
					// Aide
					{TRUE,  IDM_HELPCONTENT,		66, NULL, NULL, szMainMenuHelpContent,			0, szMainMenuKeyHelp, 0},
					{TRUE,  IDM_HELPVERSIONS,		00, NULL, NULL, szMainMenuHelpVersions,			0, NULL, 0},
					{TRUE,  IDM_HELPFIRSTRUN,		00, NULL, NULL, szMainMenuHelpFirstRun,			0, NULL, 0},
					{FALSE, IDM_ABOUT,			00, NULL, NULL, szMainMenuAbout,				0, NULL, 0}};

CUSTOMITEM		PlayersMenu[]={	{TRUE,  IDM_PLAYERS,    00, NULL, NULL, szMenuPlayers00, 0, NULL, 8},
					{TRUE,  IDM_PLAYERS1,   11, NULL, NULL, szMenuPlayers01, 0, NULL, 0},
					{TRUE,  IDM_PLAYERS2,   12, NULL, NULL, szMenuPlayers02, 0, NULL, 0},
					{TRUE,  IDM_PLAYERS3,   13, NULL, NULL, szMenuPlayers03, 0, NULL, 0},
					{TRUE,  IDM_PLAYERS4,   14, NULL, NULL, szMenuPlayers04, 0, NULL, 0},
					{TRUE,  IDM_PLAYERS5,   15, NULL, NULL, szMenuPlayers05, 0, NULL, 0},
					{TRUE,  IDM_PLAYERS6,   16, NULL, NULL, szMenuPlayers06, 0, NULL, 0},
					{TRUE,  IDM_PLAYERS7,   17, NULL, NULL, szMenuPlayers07, 0, NULL, 0},
					{FALSE, IDM_MENUCANCEL, 00, NULL, NULL, szMenuCancel,    0, NULL, 0}};

CUSTOMITEM 		GatesMenu[]={	{TRUE,  IDM_MAPWORLDHEROPORTALS, 00, NULL, NULL, szMenuGate00, 0, NULL, 8},
					{TRUE,  IDM_MAPWORLDHEROSGATE1,  18, NULL, NULL, szMenuGate01, 0, szMenuGateDM1, 0},
					{TRUE,  IDM_MAPWORLDHEROSGATE2,  18, NULL, NULL, szMenuGate02, 0, szMenuGateDM2, 0},
					{TRUE,  IDM_MAPWORLDHEROSGATE3,  18, NULL, NULL, szMenuGate03, 0, szMenuGateDM3, 0},
					{TRUE,  IDM_MAPWORLDHEROSGATE4,  18, NULL, NULL, szMenuGate04, 0, szMenuGateDM4, 0},
					{TRUE,  IDM_MAPWORLDHEROSGATE6,  18, NULL, NULL, szMenuGate06, 0, szMenuGateDM6, 0},
					{TRUE,  IDM_MAPWORLDHEROSGATE7,  18, NULL, NULL, szMenuGate07, 0, szMenuGateDM7, 0},
					{FALSE, IDM_MENUCANCEL,		 00, NULL, NULL, szMenuCancel, 0, NULL, 0}};

CUSTOMITEM		ZoomMenu[]={	{TRUE,  IDM_ZOOM,	00, NULL, NULL, szMenuZoom,     0, NULL, 8},
					{TRUE,  IDM_ZOOMM5,	00, NULL, NULL, szMenuZoomM5,   0, NULL, 1},
					{TRUE,  IDM_ZOOMM4,	00, NULL, NULL, szMenuZoomM4,   0, NULL, 1},
					{TRUE,  IDM_ZOOMM3,	00, NULL, NULL, szMenuZoomM3,   0, NULL, 1},
					{TRUE,  IDM_ZOOMM2,	00, NULL, NULL, szMenuZoomM2,   0, NULL, 1},
					{TRUE,  IDM_ZOOMM1,	00, NULL, NULL, szMenuZoomM1,   0, NULL, 1},
					{TRUE,  IDM_ZOOMM0,	00, NULL, NULL, szMenuZoomM0,   0, NULL, 1},
					{TRUE,  IDM_ZOOMP1,	00, NULL, NULL, szMenuZoomP1,   0, NULL, 1},
					{TRUE,  IDM_ZOOMP2,	00, NULL, NULL, szMenuZoomP2,   0, NULL, 1},
					{TRUE,  IDM_ZOOMP3,	00, NULL, NULL, szMenuZoomP3,   0, NULL, 1},
					{TRUE,  IDM_ZOOMP4,	00, NULL, NULL, szMenuZoomP4,   0, NULL, 1},
					{TRUE,  IDM_ZOOMP5,	00, NULL, NULL, szMenuZoomP5,   0, NULL, 1},
					{TRUE,  IDM_ZOOMUSER1,	00, NULL, NULL, szMenuZoomUT,   0, NULL, 1|2},
					{TRUE,  IDM_ZOOMUSER2,	00, NULL, NULL, szMenuZoomU1,   0, NULL, 0},
					{FALSE, IDM_MENUCANCEL,	00, NULL, NULL, szMenuCancel,   0, NULL, 0}};

