
#include "..\Includes\Editor.h"
#include "..\Includes\Texts.h"

/*** Table de couleurs pour les salles **********************************/

DWORD			WorldCols[]=	{THUMB_LIMIT,
					 THUMB_WATER,
					 THUMB_LAVA,
					 THUMB_GOLD,
					 THUMB_GEMS,
					 THUMB_SOLID,
					 THUMB_ROCK,
					 THUMB_UNCLAIMED,
					 THUMB_HEROREST,
					 THUMB_NEUTRALROOM,
					 THUMB_LIMIT};

DWORD			RoomsCols[][7]={{THUMB_HEROHEART, THUMB_NEUTRALHEART, THUMB_KEEPER1HEART, THUMB_KEEPER2HEART, THUMB_KEEPER3HEART, THUMB_KEEPER4HEART, THUMB_KEEPER5HEART},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROPORTAL,THUMB_NEUTRALPORTAL,THUMB_KEEPER1PORTAL,THUMB_KEEPER2PORTAL,THUMB_KEEPER3PORTAL,THUMB_KEEPER4PORTAL,THUMB_KEEPER5PORTAL},
					{THUMB_HEROPORTAL,THUMB_NEUTRALPORTAL,THUMB_KEEPER1PORTAL,THUMB_KEEPER2PORTAL,THUMB_KEEPER3PORTAL,THUMB_KEEPER4PORTAL,THUMB_KEEPER5PORTAL},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM},
					{THUMB_HEROROOM,  THUMB_NEUTRALROOM,  THUMB_KEEPER1ROOM,  THUMB_KEEPER2ROOM,  THUMB_KEEPER3ROOM,  THUMB_KEEPER4ROOM,  THUMB_KEEPER5ROOM}};

DWORD			WallsCols[]=	{THUMB_HEROWALL,
					 THUMB_HERO,
					 THUMB_NEUTRALWALL,
					 THUMB_NEUTRAL,
					 THUMB_KEEPER1WALL,
					 THUMB_KEEPER1,
					 THUMB_KEEPER2WALL,
					 THUMB_KEEPER2,
					 THUMB_KEEPER3WALL,
					 THUMB_KEEPER3,
					 THUMB_KEEPER4WALL,
					 THUMB_KEEPER4,
					 THUMB_KEEPER5WALL,
					 THUMB_KEEPER5};

PLAYERINFO		Players[]={	{szHeros,  THUMB_HEROHEART},
					{szNeutral,THUMB_NEUTRALHEART},
					{szKeeper1,THUMB_KEEPER1HEART},
					{szKeeper2,THUMB_KEEPER2HEART},
					{szKeeper3,THUMB_KEEPER3HEART},
					{szKeeper4,THUMB_KEEPER4HEART},
					{szKeeper5,THUMB_KEEPER5HEART},
					{NULL,     0x00000000}};

