
/*** Textes (bibliothèque uniquement) ***********************************/

#ifdef CAMERAPATHDLL

char	szLF[]					= "\n";
char	szNumber[]				= "%ld";
char	szDialogClass[]				= "MapEditorPathsDialog32";
char	szDialogErr[]				= "Une erreur s'est produite lors de la création de la boîte de dialogue.";
char	szCameraPath000[]			= "Mouvement de rotation et de zoom autour de la zone spécifiée. Coïncide avec l'animation de la création du coeur du donjon.\r\nLe mouvement commence par un zoom maximum au centre de la zone. La caméra se déplace ensuite sur le côté et tremble légèrement. Après quelques secondes, elle effectue un mouvement pour avoir une vue plongeante sur le centre de la zone.";
char	szCameraPath001[]			= "Mouvement de rotation et de zoom autour de la zone spécifiée. Coïncide avec l'animation de la création du coeur du donjon.\r\nLe mouvement commence par un zoom maximum au centre de la zone. La caméra se déplace ensuite sur le côté, en surplomb, et elle tremble légèrement. Au bout d'un moment, elle effectue un mouvement pour avoir une vue plongeante sur le centre de la zone.";
char	szCameraPath002[]			= "Mouvement de rotation et de zoom autour de la zone spécifiée. Coïncide avec l'animation de la création du coeur du donjon.\r\nLe mouvement commence par un zoom maximum au centre de la zone. La caméra se déplace ensuite légèrement sur le côté pour avoir une vue plongeante sur le centre de la zone et elle se met à trembler. Après quelques secondes, elle effectue un déplacement latéral sans changer de hauteur.";
char	szCameraPath003[]			= "Mouvement de rotation et de zoom autour de la zone spécifiée. Coïncide avec l'animation de la création du coeur du donjon.\r\nLe mouvement est sensiblement le même que le précédent sauf que la scène cinématique se termine par un fondu.";
char	szCameraPath050[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLa caméra effectue une lente rotation afin de se positionner face à la zone spécifiée en zoomant un maximum dessus.";
char	szCameraPath051[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLe mouvement commence par un zoom sur le centre de la zone spécifiée puis la caméra effectue un lente rotation en s'éloignant de ce point.";
char	szCameraPath052[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLe mouvement débute un peu en retrait du centre de la zone. La caméra s'en approche ensuite lentement. Lorsqu'elle se trouve au centre de la zone, la caméra effectue un zoom arrière tout en restant braquée sur le point central de la zone. L'animation se termine par un fondu rapide.";
char	szCameraPath053[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nAu départ, la caméra est braquée sur le plafond, légèrement en retrait du centre de la zone. Ensuite, elle se penche en avant afin de montrer le centre et elle s'élève doucement vers le plafond. Le mouvement s'achève par un fondu.";
char	szCameraPath054[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLa caméra commence plaquée au sol, braquée sur le centre de la zone. Elle s'élève ensuite doucement tout en se penchant vers le centre. Le mouvement continue de la même façon, la caméra s'éloignant du sol, toujours braquée vers le centre, tandis que l'écran s'assombrit peu à peu.";
char	szCameraPath055[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nAu départ, la caméra est placée perpendiculairement au centre de la zone, plaquée au sol. Elle recule ensuite doucement. Enfin, elle s'élève vers le plafond en se penchant vers le centre de la zone.";
char	szCameraPath056[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLa caméra commence au milieu de la zone, braquée sur le plafond. Elle effectue ensuite un rapide mouvement en arrière. Enfin, elle s'élève afin d'avoir une vue plongeante sur le centre de la zone.";
char	szCameraPath057[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nAu départ, la caméra est au centre de la zone. Elle s'en éloigne rapidement et effectue une rotation afin de se placer à côté. Elle reste un léger instant dans cette position puis tourne à nouveau pour être dos au centre de la zone.";
char	szCameraPath058[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLa caméra bouge doucement en restant constamment braquée sur le centre de la zone.";
char	szCameraPath059[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLe mouvement débute comme le précédent sauf qu'à la fin, la caméra se déplace pour montrer le côté du centre de la zone.";
char	szCameraPath060[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLa caméra part du dessus et descend sans quitter l'objectif du centre de la zone. Elle s'arrète à hauteur du sol, légèrement à côté du centre.";
char	szCameraPath061[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nCe mouvement est sensiblement le même que le précédent sauf que la caméra part de moins haut.";
char	szCameraPath062[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLa caméra part du centre de la zone, effectue un zoom arrière rapide et bascule sur le côté. La scène est extrêmement rapide.";
char	szCameraPath063[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLa caméra effectue une rotation au centre de la zone et elle s'en éloigne ensuite légèrement.";
char	szCameraPath064[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLa caméra commence en surplomb du centre de la zone. Elle descend jusqu'à frôler le sol puis remonte légèrement.";
char	szCameraPath065[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLa caméra commence en surplomb du centre de la zone. Elle descend jusqu'au sol tout en élevant son objectif pour montrer le plafond. Après une courte pause, elle se tourne pour montrer le côté de la partie centrale et l'animation s'achève.";
char	szCameraPath066[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLa caméra plonge vers le centre de la zone puis effectue une rotation pour montrer le côté de la partie centrale. Le mouvement dure très peu de temps.";
char	szCameraPath067[]			= "Ce mouvement est généralement utilisé lorsqu'une créature sort d'un portail.\r\nLa caméra part du centre de la zone. Elle monte légèrement pour montrer le plafond, se baisse à nouveau puis s'éloigne un peu du centre. La séquence n'est pas très longue.";
char	szCameraPath100[]			= "La caméra effectue un flottement au milieu de la zone. L'objectif est toujours fixé sur le sol. Le mouvement dure peu de temps.";
char	szCameraPath101[]			= "La caméra part du plafond, tangue doucement perpendiculairement au sol puis s'abaisse pour que l'objectif soit fixé sur le centre de la zone. La caméra s'en éloigne alors tandis qu'un fondu très lent se met en place.";
char	szCameraPath150[]			= "La caméra part du plafond, effectue un quart de cercle autour de la zone en tremblant. Au bout d'un moment, elle s'éloigne de la partie centrale. Un fondu met fin à la scène.";
char	szCameraPath201[]			= "Ce mouvement est utilisé dans le premier niveau du jeu.\r\nLa caméra effectue toute une série de mouvements (flottement, rotations, zooms, etc.) autour du centre de la zone spécifiée. Elle s'achève par une rotation rapide et un fondu.";
char	szCameraPath203[]			= "Ce mouvement est utilisé dans le niveau 3 du jeu.\r\nLa caméra effectue une rotation au centre de la zone (1) puis elle se déplace suivant le chemin indiqué (2, 3 et 4).";
char	szCameraPath204[]			= "Ce mouvement est utilisé dans le niveau 4 du jeu.\r\nLa caméra commence au centre de la zone spécifiée (1) et s'en éloigne progressivement. Elle suit ensuite le chemin indiqué (2, 3 et 4).";
char	szCameraPath205[]			= "Ce mouvement est utilisé dans le niveau 5 du jeu.\r\nLa caméra commence au centre de la zone spécifiée (1) et s'en éloigne progressivement jusqu'au second point (2). Elle effectue ensuite une rotation tout en se rendant à un troisième point plus éloigné (3). Le mouvement ce termine par une rotation de la caméra autour de ce point.";
char	szCameraPath206[]			= "Ce mouvement est utilisé dans le niveau 6A du jeu.\r\nLa caméra commence par une rotation au centre de la zone spécifiée (1) et elle s'en éloigne jusqu'au second point (2). Là, elle tourne sur elle-même afin de se positionner de façon à rejoindre le dernier point (3). Le caméra effectue alors une rotation dans ce point. Le mouvement se termine après une courte pause.";
char	szCameraPath207[]			= "Ce mouvement est utilisé dans le niveau 7 du jeu.\r\nLa caméra commence par s'animer autour de la zone spécifiée (1), elle se dirige ensuite vers le deuxième point (2) et elle fait demi-tour pour rejoindre le dernier point (3). Une fois ce point atteint, la caméra se pose et la scène se termine après un court laps de temps.";
char	szCameraPath208[]			= "Ce mouvement est utilisé dans le niveau 8 du jeu.\r\nLa caméra commence pour tourner autour de la partie centrale de la zone. Elle s'en éloigne ensuite lentement, s'en rapproche à nouveau puis s'en éloigne encore. A la fin de l'animation, la caméra opère une courte pause et le mouvement s'achève.";
char	szCameraPath209[]			= "Ce mouvement est utilisé dans le niveau 9 du jeu.\r\nLa caméra s'élève lentement dans la zone spécifiée (1) puis se déplace jusqu'au deuxième point (2). Là, elle opère une pause avant de se rendre au dernier point (3). Après une courte pause, la scène cinématique s'achève.";
char	szCameraPath210[]			= "Ce mouvement est utilisé dans le niveau 10 du jeu.\r\nLa caméra s'éloigne lentement du centre de la zone spécifiée (1) en s'élevant, elle trace un légère courbe pour rejoindre le deuxième point (2) tout en s'abaissant un peu. Elle rejoint ensuite le troisième point (3). Tout en rejoignant le dernier point (4), la caméra opère une rotation de 360° afin de faire face à ce point. Elle refait ensuite un demi-tour lorsqu'elle arrive au dernier point pour faire face à l'avant-dernier point.";
char	szCameraPath211[]			= "Ce mouvement est utilisé dans le niveau 11A du jeu.\r\nLa caméra suit les différents points en partant de la zone spécifiée (1) et en s'animant autour de chaque point.";
char	szCameraPath212[]			= "Ce mouvement est utilisé dans le niveau 12 du jeu.\r\nLa caméra s'éloigne du point central de la zone (1) et donne un aperçu des terrains environnants. Ensuite, elle trace une grande courbe afin de rejoindre le deuxième point (2). Au cours de la dernière ligne droite, la caméra ralenti.";
char	szCameraPath213[]			= "Ce mouvement est utilisé dans le niveau 13 du jeu.\r\nLa caméra tourne autour du point central de la zone. Elle alterne zooms avants et zooms arrières durant l'animation.";
char	szCameraPath214[]			= "Ce mouvement est utilisé dans le niveau 14 du jeu.\r\nLa caméra commence par faire un quart de tour dans la zone spécifiée (1) puis descend rejoindre le deuxième point (2). Après une rapide animation, elle se dirige vers le troisième point (3). Là-bas, elle fait d'abord un zoom arrière puis un zoom avant rapide. La cinématique s'achève par un fondu rapide.";
char	szCameraPath215[]			= "Ce mouvement est utilisé dans le niveau 15 du jeu.\r\nLa caméra effectue une rotation et un zoom autour de chaque point. Elle part de la zone spécifié (1) et parcours les points dans l'ordre (en effectuant parfois des demi-tours et des rotations).";
char	szCameraPath216[]			= "Ce mouvement est utilisé dans le niveau 16 du jeu.\r\nLa caméra s'éloigne lentement de la partie centrale de la zone (1) en décrivant une courbe. Elle se dirige ensuite vers le second point (2) en accélérant doucement.";
char	szCameraPath217[]			= "Ce mouvement est utilisé dans le niveau 17 du jeu.\r\nLa caméra débute au centre de la zone (1), l'objectif étant braqué sur le sol. Elle s'éloigne ensuite du centre et effectue une rotation de 180° autour du point central de la zone. La rotation effectuée, elle se déplace pour rejoindre le deuxième point (2).";
char	szCameraPath218[]			= "Ce mouvement est utilisé dans le niveau 18 du jeu.\r\nLa caméra suit le chemin indiqué en partant du première point (1) et en effectuant une courte pause à chaque point. Elle effectue diverses rotations et zooms durant son chemin.";
char	szCameraPath219[]			= "Ce mouvement est utilisé dans le niveau 19 du jeu.\r\nLa caméra s'éloigne doucement du point central de la zone (1) et effectue une rotation afin de rejoindre le deuxième point (2). Au deuxième point, elle effectue à nouveau une rotation et se dirige à reculons vers le troisième point (3). Là, elle tourne de façon à être face au dernier point (4) et s'y dirige lentement. Lorsqu'elle arrive au dernier point, elle effectue une dernière rotation et s'éloigne du sol. Après une courte pause, la scène cinématique s'achève.";
char	szCameraPath221[]			= "Ce mouvement est utilisé dans le niveau 11B du jeu.\r\nC'est le même mouvement que le chemin n°211 sauf que le deuxième point est plus éloigné du premier.";
char	szCameraPath222[]			= "Ce mouvement est utilisé dans le niveau 11C du jeu.\r\nLa caméra suit le différents points en partant de la zone spécifiée (1) et en s'animant autour de chaque point.";
char	szCameraPath230[]			= "Dans ce mouvement, la caméra est surélevée, elle est braquée sur le centre de la zone et tourne rapidement autour de ce dernier. La scène est relativement rapide.";
char	szCameraPath231[]			= "Dans ce mouvement, la caméra est surélevée, elle est braquée sur le centre de la zone et tourne autour de ce dernier jusqu'à ce qu'elle ait effectué environ un quart de cercle.";
char	szCameraPath232[]			= "Dans ce mouvement, la caméra est surélevée, elle est braquée sur le centre de la zone et tourne autour de ce dernier jusqu'à ce qu'elle ait effectué un tour complet.";
char	szCameraPath233[]			= "Le mouvement ressemble à peu de chose près au chemin de caméra n°231 sauf qu'il est plus lent.";
char	szCameraPath234[]			= "Dans ce mouvement, la caméra est surélevée donnant ainsi une large vision de la scène. Elle est braquée sur le centre de la zone et tourne autour de ce dernier.";
char	szCameraPath235[]			= "La caméra effectue sensiblement le même mouvement que précédemment sauf qu'elle le fait plus lentement et sur un tour complet (ou presque).";
char	szCameraPath236[]			= "Le mouvement est sensiblement le même que précédemment.";

#endif

