
/*** Textes des menus ***************************************************/

char	szMainMenuNew[]				= "Nouvelle carte...";
char	szMainMenuDisk[]			= "Chargement et Sauvegarde";
char	szMainMenuOpen[]			= "Ouvrir...";
char	szMainMenuRecent[]			= "Ouvrir à nouveau...";
char	szMainMenuSave[]			= "Sauver";
char	szMainMenuSaveAs[]			= "Sauver en...";
char	szMainMenuCompilation[]			= "Compilation";
char	szMainMenuCompile[]			= "Compiler";
char	szMainMenuTest[]			= "Tester";
char	szMainMenuExecute[]			= "Exécuter";
char	szMainMenuQuit[]			= "Quitter";
char	szMainMenuUndo[]			= "Annulation";
char	szMainMenuUndoLast[]			= "Annuler la dernière opération";
char	szMainMenuUndoMnu[]			= "Gestion de l'annulation...";
char	szMainMenuUndoHistory[]			= "Afficher l'historique des opérations";
char	szMainMenuUndoFree[]			= "Libérer la mémoire utilisée par l'annulation";
char	szMainMenuUndoCount[]			= "Changer le nombre d'opérations mémorisées";
char	szMainMenuSelRect[]			= "Rectangle de sélection";
char	szMainMenuCopy[]			= "Copier";
char	szMainMenuCut[]				= "Couper";
char	szMainMenuPaste[]			= "Coller";
char	szMainMenuLoadBrush[]			= "Charger...";
char	szMainMenuLoadBrushInSel[]		= "Une zone sauvegardée et la coller dans la sélection";
char	szMainMenuLoadBrushInCopy[]		= "Une zone sauvegardée et la stocker dans la mémoire de copie";
char	szMainMenuSaveBrush[]			= "Sauvegarder...";
char	szMainMenuSelection[]			= "La sélection";
char	szMainMenuCopyZone[]			= "La zone copiée";
char	szMainMenuTransform[]			= "Tranformation...";
char	szMainMenuRotateP90[]			= "Rotation de 90° horaires";
char	szMainMenuRotateM90[]			= "Rotation de 90° anti-horaires";
char	szMainMenuSymHorz[]			= "Symétrie axe horizontal";
char	szMainMenuSymVert[]			= "Symétrie axe vertical";
char	szMainMenuSelectChange[]		= "Changer la sélection";
char	szMainMenuSelectAll[]			= "Tout sélectionner";
char	szMainMenuSelectNone[]			= "Désélectionner";
char	szMainMenuSearch[]			= "Recherche";
char	szMainMenuFind[]			= "Rechercher...";
char	szMainMenuPaintBrush[]			= "Motif du dessin";
char	szMainMenuWorldElem[]			= "Eléments du monde";
char	szMainMenuRooms[]			= "Salles";
char	szMainMenuPaintMode[]			= "Mode de dessin";
char	szMainMenuRect[]			= "Rectangle";
char	szMainMenuRectRnd[]			= "Rectangle aléatoire";
char	szMainMenuRectFill[]			= "Rectangle avec remplissage";
char	szMainMenuRectFillRnd[]			= "Rectangle avec remplissage aléatoire";
char	szMainMenuCircle[]			= "Ellipse";
char	szMainMenuCircleRnd[]			= "Ellipse aléatoire";
char	szMainMenuCircleFill[]			= "Ellipse avec remplissage";
char	szMainMenuCircleFillRnd[]		= "Ellipse avec remplissage aléatoire";
char	szMainMenuLine[]			= "Ligne";
char	szMainMenuLineRnd[]			= "Ligne aléatoire";
char	szMainMenuPen[]				= "Crayon";
char	szMainMenuFill[]			= "Remplissage";
char	szMainMenuPutElem[]			= "Placer un élément...";
char	szMainMenuPutCreature[]			= "Placer une créature";
char	szMainMenuPutDoor[]			= "Placer une porte";
char	szMainMenuPutTrap[]			= "Placer un piège";
char	szMainMenuPutObject[]			= "Placer un objet";
char	szMainMenuPutMagicalObject[]		= "Placer un objet magique";
char	szMainMenuModifyCreature[]		= "Modifier la créature à placer";
char	szMainMenuModifyDoor[]			= "Modifier la porte à placer";
char	szMainMenuModifyTrap[]			= "Modifier le piège à placer";
char	szMainMenuModifyObject[]		= "Modifier l'objet à placer";
char	szMainMenuModifyMagicalObject[]		= "Modifier l'objet magique à placer";
char	szMainMenuCreatures[]			= "Gestion des créatures";
char	szMainMenuDoorsTraps[]			= "Gestion des portes et des pièges";
char	szMainMenuObjects[]			= "Gestion des objets";
char	szMainMenuOthers[]			= "Autres";
char	szMainMenuHeros[]			= "Gestion des héros";
char	szMainMenuAreas[]			= "Gestion des zones";
char	szMainMenuGates[]			= "Gestion des passages";
char	szMainMenuPaths[]			= "Gestion des chemins de ronde";
char	szMainMenuEffects[]			= "Gestion des effets";
char	szMainMenuEvents[]			= "Gestion des évènements";
char	szMainMenuCreaturesProperties[]		= "Propriétés des créatures";
char	szMainMenuGameProperties[]		= "Propriétés des éléments";
char	szMainMenuMapProperties[]		= "Propriétés de la carte";
char	szMainMenuThumbnail[]			= "Réduction";
char	szMainMenuFullScreen[]			= "Carte plein-écran";
char	szMainMenuMapStats[]			= "Statistiques de la carte";
char	szMainMenuWindows[]			= "Fenêtres";
char	szMainMenuToolbar[]			= "Boîte à outils";
char	szMainMenuMinimap[]			= "Carte miniature && Informations";
char	szMainMenuMinimapParams[]		= "Paramètres de la carte miniature";
char	szMainMenuKeepProps[]			= "Conserver les proportions";
char	szMainMenuDisplayCreatures[]		= "Afficher les créatures";
char	szMainMenuDisplayDoors[]		= "Afficher les portes";
char	szMainMenuDisplayTraps[]		= "Afficher les pièges";
char	szMainMenuDisplayMagics[]		= "Afficher les objets magiques";
char	szMainMenuMap[]				= "Carte";
char	szMainMenuFlagTerrain[]			= "Terrain";
char	szMainMenuFlagCreatures[]		= "Créatures";
char	szMainMenuFlagDoors[]			= "Portes";
char	szMainMenuFlagTraps[]			= "Pièges";
char	szMainMenuFlagMagicals[]		= "Objets magiques";
char	szMainMenuFlagObjects[]			= "Objets";
char	szMainMenuFlagAreas[]			= "Zones";
char	szMainMenuFlagPaths[]			= "Chemins";
char	szMainMenuFlagGates[]			= "Passages";
char	szMainMenuFlagEffects[]			= "Effets";
char	szMainMenuFlagCameras[]			= "Caméras";
char	szMainMenuOptions[]			= "Options";
char	szMainMenuMoreDetails[]			= "Détailler le nombre de créatures";
char	szMainMenuExpandGates[]			= "Etendre les passages";
char	szMainMenuObjectsColor[]		= "Utiliser les couleurs des joueurs pour les objets";
char	szMainMenuMagicsColor[]			= "Utiliser les couleurs des joueurs pour les objets magiques";
char	szMainMenuProperties[]			= "Modifier les paramètres du programme";
char	szMainMenuPropertiesSave[]		= "Sauvegarder les paramètres à la sortie";
char	szMainMenuPropertiesSaveNow[]		= "Sauvegarder les paramètres maintenant";
char	szMainMenuHelpContent[]			= "Contenu";
char	szMainMenuHelpFirstRun[]		= "Premiers pas";
char	szMainMenuHelpVersions[]		= "Versions de la carte";
char	szMainMenuAbout[]			= "A propos de...";
char	szMainMenuHeroPortals[]			= "Portails des héros";
char	szMainMenuPlayers[]			= "Joueurs";

char	szMainMenuKeyNew[]			= "Shift + Ctrl + N";
char	szMainMenuKeyOpen[]			= "Ctrl + O";
char	szMainMenuKeySave[]			= "Ctrl + S";
char	szMainMenuKeyCompile[]			= "Shift + Ctrl + C";
char	szMainMenuKeyTest[]			= "Shift + Ctrl + T";
char	szMainMenuKeyExecute[]			= "Shift + Ctrl + E";
char	szMainMenuKeyUndoLast[]			= "Ctrl + Z";
char	szMainMenuKeyCopy[]			= "Ctrl + C";
char	szMainMenuKeyCut[]			= "Ctrl + X";
char	szMainMenuKeyPaste[]			= "Ctrl + V";
char	szMainMenuKeyRotateP90[]		= "Ctrl + R";
char	szMainMenuKeyRotateM90[]		= "Shift + Ctrl + R";
char	szMainMenuKeySymHorz[]			= "Ctrl + Y";
char	szMainMenuKeySymVert[]			= "Shift + Ctrl + Y";
char	szMainMenuKeySelectAll[]		= "Ctrl + A";
char	szMainMenuKeySelectNone[]		= "Ctrl + N";
char	szMainMenuKeyFind[]			= "Ctrl + F";
char	szMainMenuKeyRect[]			= "Ctrl + f1";
char	szMainMenuKeyRectFill[]			= "Ctrl + f2";
char	szMainMenuKeyCircle[]			= "Ctrl + f3";
char	szMainMenuKeyCircleFill[]		= "Ctrl + f4";
char	szMainMenuKeyLine[]			= "Ctrl + f5";
char	szMainMenuKeyPen[]			= "Ctrl + f6";
char	szMainMenuKeyFill[]			= "Ctrl + f7";
char	szMainMenuKeyPutCreature[]		= "Shift + Ctrl + f1";
char	szMainMenuKeyPutDoor[]			= "Shift + Ctrl + f2";
char	szMainMenuKeyPutTrap[]			= "Shift + Ctrl + f3";
char	szMainMenuKeyPutObject[]		= "Shift + Ctrl + f4";
char	szMainMenuKeyPutMagicalObject[]		= "Shift + Ctrl + f5";
char	szMainMenuKeyHelp[]			= "f1";

char	szMenuPlayers00[]			= "Sélection du joueur";
char	szMenuPlayers01[]			= "Héros";
char	szMenuPlayers02[]			= "Neutre";
char	szMenuPlayers03[]			= "Gardien 1";
char	szMenuPlayers04[]			= "Gardien 2";
char	szMenuPlayers05[]			= "Gardien 3";
char	szMenuPlayers06[]			= "Gardien 4";
char	szMenuPlayers07[]			= "Gardien 5";
char	szMenuCancel[]				= "Abandon";

char	szMenuGate00[]				= "Sélection du portail des héros";
char	szMenuGate01[]				= " 1 -- Portail dans grande salle voûtée -- Vers Sud";
char	szMenuGate02[]				= " 2 -- Portail incrusté dans de la roche dure";
char	szMenuGate03[]				= " 3 -- Portail voûté";
char	szMenuGate04[]				= " 4 -- Portail dans grande salle de présentation -- Vers Sud";
char	szMenuGate06[]				= " 6 -- Portail horizontal";
char	szMenuGate07[]				= " 7 -- Portail vertical";

char	szMenuGateDM1[]				= "(L 3 x Hmin 1)";
char	szMenuGateDM2[]				= "(Lmin 1 x Hmin 1)";
char	szMenuGateDM3[]				= "(L 2 x H 2)";
char	szMenuGateDM4[]				= "(L 3 x Hmin 2)";
char	szMenuGateDM5[]				= "(Lmin 1 x Hmin 1)";
char	szMenuGateDM6[]				= "(L 3 x H 1)";
char	szMenuGateDM7[]				= "(L 1 x H 3)";

char	szMenuZoom[]				= "Sélection du zoom";
char	szMenuZoomM5[]				= "10x10 pixels";		// 00
char	szMenuZoomM4[]				= "16x16 pixels";		// 01
char	szMenuZoomM3[]				= "20x20 pixels";		// 02
char	szMenuZoomM2[]				= "32x32 pixels";		// 03
char	szMenuZoomM1[]				= "40x40 pixels";		// 04
char	szMenuZoomM0[]				= "48x48 pixels (par défaut)";	// 05
char	szMenuZoomP1[]				= "60x60 pixels";		// 06
char	szMenuZoomP2[]				= "80x80 pixels";		// 07
char	szMenuZoomP3[]				= "96x96 pixels";		// 08
char	szMenuZoomP4[]				= "100x100 pixels";		// 09
char	szMenuZoomP5[]				= "128x128 pixels";		// 10
char	szMenuZoomU0[]				= "%ldx%ld pixels (personnalisé)";// 11
char	szMenuZoomU1[]				= "Modifier le zoom personnalisé";
char	szMenuZoomUT[]				= "000x000 pixels (personnalisé)";

