
#define IDM_MENUCANCEL				60000

/*** Menu principal **************************************************************/

//--- Menu Fichier ---

#define IDM_RECENTITEMSFIRST			10000
#define IDM_RECENTITEMSMAX			10032

#define IDM_NEW					100
#define IDM_DISK				101
#define IDM_OPEN				102
#define IDM_RECENT				103
#define IDM_SAFEFILE				104
#define IDM_RECENTREMOVEOBSOLETE		105
#define IDM_RECENTREMOVEALL			106
#define IDM_SAVE				107
#define IDM_SAVEAS				108
#define IDM_COMPILATION				109
#define IDM_COMPILE				110
#define IDM_TEST				111
#define IDM_EXECUTE				112
#define IDM_QUIT				113

//--- Menu Edition ---

#define IDM_UNDO				200
#define IDM_UNDOLAST				201
#define IDM_UNDOMNU				202
#define IDM_UNDOHISTORY				203
#define IDM_UNDOFREE				204
#define IDM_UNDOCOUNT				205

#define IDM_SELRECT				206
#define IDM_COPY				207
#define IDM_CUT					208
#define IDM_PASTE				209
#define IDM_LOADBRUSH				210
#define IDM_LOADBRUSHINSEL			211
#define IDM_LOADBRUSHINCOPY			212
#define IDM_SAVEBRUSH				213
#define IDM_SELECTION				214
#define IDM_COPYZONE				215
#define IDM_TRANSFORM				216
#define IDM_ROTATEP90				217
#define IDM_ROTATEM90				218
#define IDM_SYMHORZ				219
#define IDM_SYMVERT				220
#define IDM_SELECTCHANGE			221
#define IDM_SELECTALL				222
#define IDM_SELECTNONE				223

#define IDM_SEARCH				230
#define IDM_FIND				231

#define IDM_WORLDELEMENTS			240
#define IDM_CREATURES				241
#define IDM_DOORSTRAPS				242
#define IDM_OBJECTS				243

#define IDM_OTHERS				250
#define IDM_HEROS				251
#define IDM_AREAS				252
#define IDM_GATES				253
#define IDM_PATHS				255
#define IDM_EFFECTS				256
#define IDM_EVENTS				257
#define IDM_CREATURESPROPERTIES			258
#define IDM_GAMEPROPERTIES			259
#define IDM_MAPPROPERTIES			260

//--- Menu Dessin ---

#define IDM_PAINTBRUSH				300

#define IDM_WORLDELEM				301
#define IDM_MAPWORLDLIMIT			302
#define IDM_MAPWORLDWATER			303
#define IDM_MAPWORLDLAVA			304
#define IDM_MAPWORLDGOLD			305
#define IDM_MAPWORLDGEMS			306
#define IDM_MAPWORLDSOLID			307
#define IDM_MAPWORLDROCK			308
#define IDM_MAPWORLDUNCLAIMED			309
#define IDM_MAPWORLDHEROREST			310
#define IDM_MAPWORLDMANACLOSED			311

#define IDM_MAPWORLDSTRT			IDM_MAPWORLDLIMIT
#define IDM_MAPWORLDSTOP			IDM_MAPWORLDMANACLOSED

#define IDM_MAPWORLDHEROPORTALS			312
#define IDM_MAPWORLDHEROSGATE1			313
#define IDM_MAPWORLDHEROSGATE2			314
#define IDM_MAPWORLDHEROSGATE3			315
#define IDM_MAPWORLDHEROSGATE4			316
#define IDM_MAPWORLDHEROSGATE6			317
#define IDM_MAPWORLDHEROSGATE7			318

#define IDM_MAPWORLDHEROPORTALSSTRT		IDM_MAPWORLDHEROSGATE1
#define IDM_MAPWORLDHEROPORTALSSTOP		IDM_MAPWORLDHEROSGATE7

#define IDM_ROOMS				320

#define IDM_PLAYERS				321
#define IDM_PLAYERS1				322
#define IDM_PLAYERS2				323
#define IDM_PLAYERS3				324
#define IDM_PLAYERS4				325
#define IDM_PLAYERS5				326
#define IDM_PLAYERS6				327
#define IDM_PLAYERS7				328

#define IDM_PLAYERSSTRT				IDM_PLAYERS1
#define IDM_PLAYERSSTOP				IDM_PLAYERS7

#define IDM_MAPWORLDWALL			330
#define IDM_MAPWORLDCLAIMED			331
#define IDM_MAPWORLDHEART			332
#define IDM_MAPWORLDLAIR			333
#define IDM_MAPWORLDLIBRARY			334
#define IDM_MAPWORLDTREASURY			335
#define IDM_MAPWORLDCASINO			336
#define IDM_MAPWORLDWOODENBRIDGEWATER		337
#define IDM_MAPWORLDWOODENBRIDGELAVA		338
#define IDM_MAPWORLDTORTURE			339
#define IDM_MAPWORLDGRAVEYARD			340
#define IDM_MAPWORLDTEMPLE			341
#define IDM_MAPWORLDHEROSBRIDGEWATER		342
#define IDM_MAPWORLDHEROSBRIDGELAVA		343
#define IDM_MAPWORLDMERCENARIES			344
#define IDM_MAPWORLDPORTAL			345
#define IDM_MAPWORLDHATCHERY			346
#define IDM_MAPWORLDTRAINING			347
#define IDM_MAPWORLDWORKSHOP			348
#define IDM_MAPWORLDGUARD			349
#define IDM_MAPWORLDPRISON			350
#define IDM_MAPWORLDSTONEBRIDGEWATER		351
#define IDM_MAPWORLDSTONEBRIDGELAVA		352
#define IDM_MAPWORLDPIT				353
#define IDM_MAPWORLDMANAOPENED			354

#define IDM_ROOMSSTRT				IDM_MAPWORLDHEART
#define IDM_ROOMSSTOP				IDM_MAPWORLDMANAOPENED

#define IDM_PAINTMODE				360
#define IDM_RECT				361
#define IDM_RECTFILL				362
#define IDM_CIRCLE				363
#define IDM_CIRCLEFILL				364
#define IDM_LINE				365
#define IDM_PEN					366
#define IDM_FILL				367
#define IDM_PUTELEM				368

#define IDM_PAINTMODESTRT			IDM_RECT
#define IDM_PAINTMODESTOP			IDM_PUTELEM

#define IDM_PUTCREATURE				370
#define IDM_PUTDOOR				371
#define IDM_PUTTRAP				372
#define IDM_PUTOBJECT				373
#define IDM_PUTMAGICALOBJECT			374

#define IDM_PUTSTRT				IDM_PUTCREATURE
#define IDM_PUTSTOP				IDM_PUTMAGICALOBJECT

#define IDM_MODIFYCREATURE			375
#define IDM_MODIFYDOOR				376
#define IDM_MODIFYTRAP				377
#define IDM_MODIFYOBJECT			378
#define IDM_MODIFYMAGICALOBJECT			379

#define IDM_MODIFYSTRT				IDM_MODIFYCREATURE
#define IDM_MODIFYSTOP				IDM_MODIFYMAGICALOBJECT

//--- Menu Afficher ---

#define IDM_WINDOWS				400
#define IDM_THUMBNAIL				401
#define IDM_FULLSCREEN				402
#define IDM_MAPSTATS				403
#define IDM_TOOLBAR				404
#define IDM_MINIMAP				405

#define IDM_MINIMAPPARAMS			411
#define IDM_KEEPPROPS				412
#define IDM_DISPLAYCREATURES			413
#define IDM_DISPLAYDOORS			414
#define IDM_DISPLAYTRAPS			415
#define IDM_DISPLAYMAGICS			416

#define IDM_MAP					420
#define IDM_FLAGTERRAIN				421
#define IDM_FLAGCREATURES			422
#define IDM_FLAGDOORS				423
#define IDM_FLAGTRAPS				424
#define IDM_FLAGMAGICALS			425
#define IDM_FLAGOBJECTS				426
#define IDM_FLAGAREAS				427
#define IDM_FLAGPATHS				428
#define IDM_FLAGGATES				429
#define IDM_FLAGEFFECTS				430
#define IDM_FLAGCAMERAS				431

#define IDM_OPTIONS				440
#define IDM_MOREDETAILS				441
#define IDM_EXPANDGATES				442
#define IDM_OBJECTSCOLOR			443
#define IDM_MAGICSCOLOR				444

//--- Menu Propriétés ---

#define IDM_PROPERTIES				500
#define IDM_PROPERTIESSAVE			501
#define IDM_PROPERTIESSAVENOW			502

//--- Menu Aide ---

#define IDM_HELPCONTENT				600
#define IDM_HELPFIRSTRUN			601
#define IDM_HELPVERSIONS			610
#define IDM_ABOUT				620

/*** Menus contextuels ***********************************************************/

#define IDM_ZOOM				5000
#define IDM_ZOOMM5				5001
#define IDM_ZOOMM4				5002
#define IDM_ZOOMM3				5003
#define IDM_ZOOMM2				5004
#define IDM_ZOOMM1				5005
#define IDM_ZOOMM0				5006
#define IDM_ZOOMP1				5007
#define IDM_ZOOMP2				5008
#define IDM_ZOOMP3				5009
#define IDM_ZOOMP4				5010
#define IDM_ZOOMP5				5011
#define IDM_ZOOMUSER1				5012
#define IDM_ZOOMUSER2				5013

#define IDM_ZOOMSTRT				IDM_ZOOMM5
#define IDM_ZOOMSTOP				IDM_ZOOMUSER1

