
/*** Identificateurs ****************************************************/

#define PAINTMODE_RECT		1
#define PAINTMODE_RECTFILL	2
#define PAINTMODE_CIRCLE	3
#define PAINTMODE_CIRCLEFILL	4
#define PAINTMODE_LINE		5
#define PAINTMODE_PEN		6
#define PAINTMODE_FILL		7

#define PAINTMODE_RECTRND	11
#define PAINTMODE_RECTFILLRND	12
#define PAINTMODE_CIRCLERND	13
#define PAINTMODE_CIRCLEFILLRND	14
#define PAINTMODE_LINERND	15

#define PAINTMODE_CREATURE	50
#define PAINTMODE_DOOR		51
#define PAINTMODE_TRAP		52
#define PAINTMODE_OBJECT	53
#define PAINTMODE_MAGICALOBJECT	54

#define SELECTMODE_DEFAULT	0
#define SELECTMODE_PATH		1

