
#define DIALOG_CLASS			"MapEditorDialog32"
#define DIALOG_PATHSCLASS		"MapEditorPathsDialog32"

#define MENU_SAFEFILE			"Charger la sauvegarde automatique"
#define MENU_REMOVEOBSOLETE		"Retirer de la liste les cartes qui n'existent plus"
#define MENU_REMOVEALL			"Réinitialiser la liste"

/*** Textes des boîtes de dialogues **********************************************/

#define DIALOG_VARIABLE			"Variable"
#define DIALOG_TIMER			"Compteur"
#define DIALOG_DOORTITLE		"Sélection d'une porte..."
#define DIALOG_TRAPTITLE		"Sélection d'un piège..."
#define DIALOG_CREATURETITLE		"Sélection d'une créature..."
#define DIALOG_MAGICTITLE		"Sélection d'un objet magique..."
#define DIALOG_THINGTITLE		"Sélection d'un objet..."
#define DIALOG_NULL			""
#define DIALOG_PLAYER			"Joueur"
#define DIALOG_CREATUREOPTIONS		"Options des créatures"
#define DIALOG_HEROSPARAMS		"Paramètres des héros"
#define DIALOG_HEROSOPTIONS		"Options des héros"
#define DIALOG_HEROSOBJECTIVES		"Objectif"
#define DIALOG_ALLOPTIONS		"Options"
#define DIALOG_FILEWIDTH 		"Largeur:"
#define DIALOG_FILEHEIGHT		"Hauteur:"
#define DIALOG_FILECREATURES		"Creatures:"
#define DIALOG_FILEDOORS		"Portes:"
#define DIALOG_FILETRAPS		"Pièges:"
#define DIALOG_FILEOBJECTS		"Objets:"
#define DIALOG_FILEMAGICS		"Objets mag.:"
#define DIALOG_DOORTYPE			"Type de porte"
#define DIALOG_DOORCLOSED		"Porte fermée"
#define DIALOG_DOORBLUEPRINT		"Esquisse"
#define DIALOG_OK			"Ok"
#define DIALOG_ABORT			"Abandon"
#define DIALOG_TRAPTYPE			"Type de piège"
#define DIALOG_CREATURETYPE		"Type de créature"
#define DIALOG_VITALITY			"Santé"
#define DIALOG_MAGICTYPE		"Type d'objet magique"
#define DIALOG_THINGTYPE		"Type d'objet"

#define DIALOG_EXITERR			"Créateur de carte pour Dungeon Keeper II®"
#define DIALOG_EXIT			"Le programme ne s'est pas terminé normalement!\n\nSi la défaillance provient de l'éditeur et que le problème persiste, veuillez contacter l'auteur à l'adresse suivante:\nnov_fr@yahoo.fr\n\nN'oubliez pas de préciser votre configuration (système d'exploitation, processeur, mémoire, carte graphique, etc.) et faites une description détaillée du problème en indiquant ce que vous étiez entrain de faire à ce moment précis.\n\nSi la sauvegarde automatique a été activée, il est possible que votre travail ne soit pas complétement perdu. Si tel est le cas, vous pouvez recharger cette sauvegarde dès maintenant ou la charger plus tard en sélectionnant ""Charger la sauvegarde automatique"" dans le menu ""Fichier""."
#define DIALOG_EXITLOADSAFE		"Charger la sauvegarde automatique"
#define DIALOG_EXITCONTINUE		"Continuer sans charger la sauvegarde automatique"

#define DIALOG_OPTIONSCREATURE04	"La créature dirige le groupe"
#define DIALOG_OPTIONSCREATURE02	"La créature assiste le chef"
#define DIALOG_OPTIONSCREATURE04B	"La créature meurt instantanément"
#define DIALOG_OPTIONSCREATURE00	"La créature est indépendante"
#define DIALOG_OPTIONSCREATURE01	"La créature peut attaquer"
#define DIALOG_OPTIONSCREATURE08	"La créature peut être attaquée"
#define DIALOG_OPTIONSCREATURE10	"La créature peut rejoindre l'antre des héros"
#define DIALOG_OPTIONSCREATURE20	"La créature peut libérer ses alliés en prison"
#define DIALOG_OPTIONSCREATURE40	"La créature est déposée à l'endroit indiqué"
#define DIALOG_OPTIONSCREATURE80	"La créature apparaît assommée"
#define DIALOG_OPTIONSHEROS01		"La créature détruit les salles ennemies"
#define DIALOG_OPTIONSHEROS04		"La créature meurt instantanément"
#define DIALOG_OPTIONSHEROS02		"La créature est un jouet"
#define DIALOG_OPTIONSHEROS08		"La créature est un mercenaire"
#define DIALOG_OPTIONSOBJECTIVE0B	"Détruire les salles ennemies"
#define DIALOG_OPTIONSOBJECTIVE0C	"Détruire les murs ennemis"
#define DIALOG_OPTIONSOBJECTIVE0D	"Voler l'or de l'ennemi"
#define DIALOG_OPTIONSOBJECTIVE0E	"Voler les sorts de l'ennemi"
#define DIALOG_OPTIONSOBJECTIVE11	"Voler les caisses de l'ennemi"
#define DIALOG_OPTIONSOBJECTIVE12	"Tuer les créatures de l'ennemi"
#define DIALOG_OPTIONSOBJECTIVE13	"Attaquer l'ennemi"
#define DIALOG_OPTIONSOBJECTIVE16	"Attendre"
#define DIALOG_OPTIONSOBJECTIVE17	"Rejoindre une zone"
#define DIALOG_OPTIONSOBJECTIVE1B	"Evasion"

#define DIALOG_UNDOTITLE		"Historique de l'annulation"
#define DIALOG_UNDOLIST			"Opérations mémorisées"
#define DIALOG_UNDOTOTAL		"Total des opérations"
#define DIALOG_UNDOCHANGES		"Changements effectués"
#define DIALOG_UNDOMEMORY		"Mémoire utilisée (en octets)"

#define DIALOG_SELTITLE			"Modification du rectangle de sélection"
#define DIALOG_SELX			"X:"
#define DIALOG_SELY			"Y:"
#define DIALOG_SELWIDTH			"Largeur:"
#define DIALOG_SELHEIGHT		"Hauteur:"

#define DIALOG_THUMBTITLE		"Options d'affichage de la réduction"
#define DIALOG_THUMBWORLD		"Monde"
#define DIALOG_THUMBWORLD1		"Limites"
#define DIALOG_THUMBWORLD2		"Eau"
#define DIALOG_THUMBWORLD3		"Lave"
#define DIALOG_THUMBWORLD4		"Or"
#define DIALOG_THUMBWORLD5		"Gems"
#define DIALOG_THUMBWORLD6		"Roche impénétrable"
#define DIALOG_THUMBWORLD7		"Roche"
#define DIALOG_THUMBWORLD8		"Terrains non réclamés"
#define DIALOG_THUMBWORLD9		"Salles de repos des héros"
#define DIALOG_THUMBPLAYERS		"Joueurs"
#define DIALOG_THUMBPLAYERS1		"Murs et terrains réclamés"
#define DIALOG_THUMBPLAYERS2		"Salles"
#define DIALOG_THUMBPLAYERS3		"Portails"
#define DIALOG_THUMBPLAYERS4		"Coeurs de donjon"
#define DIALOG_THUMBCOLOR		"Couleur des zones cachées"
#define DIALOG_THUMBCOLORKEY		"Cette couleur doit être transparente"

#define DIALOG_MNGRTITLE		"Gestionnaire d'éléments"
#define DIALOG_MNGRPARAMS		"Paramètres du nouvel élément"
#define DIALOG_MNGRCREATUREOPT		"Modifier les options des créatures"
#define DIALOG_MNGRHEROOPT		"Modifier les options des héros"
#define DIALOG_MNGROBJECTIVEOPT		"Modifier l'objectif"
#define DIALOG_MNGRMODIFYPARAMS		"Modification"
#define DIALOG_MNGRMODIFYASK		"Demander les options avant de modifier"
#define DIALOG_MNGRMODIFYPREVIEW	"Afficher l'aperçu avant de modifier"
#define DIALOG_MNGRMODIFYSTART		"<< Modifier"
#define DIALOG_MNGRADDPARAMS		"Ajout"
#define DIALOG_MNGRADDASK		"Demander les paramètres avant d'ajouter"
#define DIALOG_MNGRADDPREVIEW		"Afficher l'aperçu avant d'ajouter"
#define DIALOG_MNGRADDSTART		"<< Ajouter"
#define DIALOG_MNGRPOS			"Positions"
#define DIALOG_MNGRVIEW			"Voir"
#define DIALOG_MNGRKILL			"Supprimer"
#define DIALOG_MNGRSELECTALL		"Tout sélectionner"
#define DIALOG_MNGROPTIONS		"Options"
#define DIALOG_MNGRMODIFY		"Modifier"
#define DIALOG_MNGRUNDO			"Annuler les changements"
#define DIALOG_MNGRCLOSE		"Fermer"
#define DIALOG_MNGRSHOW			"Cliquez ici pour continuer"

#define DIALOG_MNGRMODOPTIONS		"Options de modification"
#define DIALOG_MNGRMODGENERAL		"Options générales"
#define DIALOG_MNGRMODPOSITION		"Modifier la position"
#define DIALOG_MNGRMODSAMEPOS		"Utiliser la même position pour tous"
#define DIALOG_MNGRMODRELATIVEPOS	"Utiliser une position relative"
#define DIALOG_MNGRMODTYPE		"Modifier le type"
#define DIALOG_MNGRMODOWNER		"Modifier le détenteur"
#define DIALOG_MNGRMODREMPLACE		"Remplacement"
#define DIALOG_MNGRMODREMPALL		"Tout remplacer"
#define DIALOG_MNGRMODREMSAME		"Ne remplacer que les éléments identiques"
#define DIALOG_MNGRMODREMSAMEFAMILY	"Ne remplacer que les éléments de même famille"
#define DIALOG_MNGRMODREMNONE		"Ne rien remplacer"
#define DIALOG_MNGRMODREMASK		"Afficher l'aperçu"
#define DIALOG_MNGRMODPROBLEMS		"En cas de problème"
#define DIALOG_MNGRMODIGNORETERRAIN	"Ignorer les terrains incompatibles"
#define DIALOG_MNGRMODIGNOREFATALS	"Ignorer les terrains fatals"
#define DIALOG_MNGRMODIGNOREENEMIES	"Ignorer les terrains ennemies"
#define DIALOG_MNGRMODIGNOREINCOMP	"Ignorer les incompatibilités"
#define DIALOG_MNGRMODIGNOREASK		"Afficher l'aperçu"
#define DIALOG_MNGRMODSPECIALS		"Paramètres particuliers"
#define DIALOG_MNGRMODLEVEL		"Modifier le niveau"
#define DIALOG_MNGRMODGOLD		"Modifier l'or"
#define DIALOG_MNGRMODHEALTH		"Modifier la santé"
#define DIALOG_MNGRMODCROPTIONS		"Modifier les options des créatures"
#define DIALOG_MNGRMODCROPTALL		"Tout sélectionner"
#define DIALOG_MNGRMODCROPTSELECT	"Sélectionner séparément"
#define DIALOG_MNGRMODHROPTIONS		"Modifier les options des héros"
#define DIALOG_MNGRMODOBJECTIVE		"Modifier l'objectif"
#define DIALOG_MNGRMODSTATUS		"Modifier le status"
#define DIALOG_MNGRMODDATA		"Modifier la donnée"

#define DIALOG_MNGRADDOPTIONS		"Options d'ajout"
#define DIALOG_MNGRADDOPTPARAMS		"Paramètres d'ajout"
#define DIALOG_MNGRADDPOS		"Ajouter à la position spécifiée"
#define DIALOG_MNGRADDRECT		"Ajouter dans tout le rectangle"
#define DIALOG_MNGRADDRECTRANDOM	"Ajouter aléatoirement dans tout le rectangle"
#define DIALOG_MNGRADDRANDOM		"Chances (1/x)"
#define DIALOG_MNGRADDRANDOMOFTEN	"Souvent"
#define DIALOG_MNGRADDRANDOMRARELY	"Rarement"

#define DIALOG_MNGRPREVIEW		"Aperçu des changements"
#define DIALOG_MNGRPREVBEFORE		"Avant"
#define DIALOG_MNGRPREVAFTER		"Après"
#define DIALOG_MNGRPREVPROBLEMS		"Problèmes"
#define DIALOG_MNGRPREVACTIONS		"Actions"
#define DIALOG_MNGRPREVIGNORE		"Ne rien faire"
#define DIALOG_MNGRPREVREMOVE		"Supprimer"
#define DIALOG_MNGRPREVMODIFY		"Modifier"
#define DIALOG_MNGRPREVADD		"Ajouter"
#define DIALOG_MNGRPREVCONTINUE		"Continuer"

#define DIALOG_HEROSTITLE		"Héros..."
#define DIALOG_HEROSLIST		"Liste des bandes"
#define DIALOG_HEROSMODIFY		"Modifier"
#define DIALOG_HEROSKILL		"Supprimer"
#define DIALOG_HEROSADD			"Ajouter"
#define DIALOG_HEROSCLOSE		"Fermer"
#define DIALOG_HEROSEDITTITLE		"Ajout et modification d'une bande de héros..."
#define DIALOG_HEROSEDITNAME		"Nom de la bande de héros"
#define DIALOG_HEROSEDITCREATURES	"Liste des créatures"
#define DIALOG_HEROSEDITPARAMS		"Paramètres de la créature sélectionnée"
#define DIALOG_HEROSEDITLEVEL		"Niveau"
#define DIALOG_HEROSEDITOPTIONS		"Options"
#define DIALOG_HEROSEDITOBJECTIVE	"Objectif"
#define DIALOG_HEROSEDITADD		"Ajouter >>"
#define DIALOG_HEROSEDITREMPLACE	"Remplacer >>"
#define DIALOG_HEROSEDITBAND		"Bande de héros"
#define DIALOG_HEROSEDITKILL		"Supprimer le (ou les) héro(s) sélectionné(s)"
#define DIALOG_HEROSEDITMODIFY		"Modifier le héro sélectionné"

#define DIALOG_AREARECT			"Rectangle de sélection"
#define DIALOG_AREASTART		"Positions de départ"
#define DIALOG_AREAEND			"Positions d'arrivée"
#define DIALOG_AREASEPARATOR		"/"
#define DIALOG_AREARECTCOLOR		"Couleur du rectangle"
#define DIALOG_AREAMODIFY		"Modifier"
#define DIALOG_AREATEXTCOLOR		"Couleur du texte"
#define DIALOG_AREANAME			"Nom"
#define DIALOG_AREAINFO			"Description"
#define DIALOG_AREAOPTIONS		"Options"
#define DIALOG_AREAADD			"Ajouter >>"
#define DIALOG_AREALIST			"Liste"
#define DIALOG_AREAKILL			"Supprimer"
#define DIALOG_AREAMODIFY		"Modifier"
#define DIALOG_AREACLOSE		"Fermer"
#define DIALOG_AREAMODIFYRECT		"Rectangle à modifier"
#define DIALOG_AREAGETRECT		"<<"
#define DIALOG_AREAOPTTITLE		"Options de la zone"
#define DIALOG_AREAOPTHEROLAIR		"Antre des héros"
#define DIALOG_AREAOPTIGNORESOLID	"Ignorer les parties solides"
#define DIALOG_AREAOPTVISIBLE		"Visible à travers le brouillard de guerre"
#define DIALOG_AREAOPTTOOLS		"Boîte à héros (p'tit donjon)"
#define DIALOG_EFFECTOPTTITLE		"Paramètres des effets"
#define DIALOG_EFFECTOPTFREQ		"Fréquence des effets"
#define DIALOG_EFFECTOPTEFFECT1		"Premier effet"
#define DIALOG_EFFECTOPTEFFECT2		"Deuxième effet"
#define DIALOG_EFFECTOPTEFFECT3		"Troisième effet"
#define DIALOG_EFFECTOPTEFFECT4		"Quatrième effet"
#define DIALOG_EFFECTOPTOFTEN		"Souvent"
#define DIALOG_EFFECTOPTRARELY		"Très rarement"
#define DIALOG_GATEOPTTITLE		"Ajout automatique des passages"
#define DIALOG_GATEOPTADDPARAMS		"Paramètres d'ajout"
#define DIALOG_GATEOPTGATES		"Ajouter les passages nécessaires..."
#define DIALOG_GATEOPTGATES0		"...à l'affichage"
#define DIALOG_GATEOPTGATES1		"...à la destruction"
#define DIALOG_GATEOPTGATES2		"...à la libération de héros"
#define DIALOG_GATEOPTAREAS		"Ajouter les zones nécessaires..."
#define DIALOG_GATEOPTTRIGGERS		"Ajouter les évènements"
#define DIALOG_GATEOPTDISPPARAMS	"Paramètres d'affichage"
#define DIALOG_GATEOPTDISPTYPE		"Paramètres pour..."
#define DIALOG_GATEOPTGENERATE		"Ajouter"

#define DIALOG_AREAPATHTITLE		"Edition des chemins de ronde"
#define DIALOG_AREAPATHLIST		"Liste des chemins de ronde"
#define DIALOG_AREAPATHNEW		"Nouveau"
#define DIALOG_AREAPATHADD		"Ajouter"
#define DIALOG_AREAPATHINS		"Insérer"
#define DIALOG_AREAPATHSUB		"Supprimer"
#define DIALOG_AREAPATHMOD		"Pause"
#define DIALOG_AREAPATHCLOSE		"Fermer"
#define DIALOG_AREAPATHPTTITLE		"Sélection d'une zone"
#define DIALOG_AREAPATHPTLIST		"Liste des zones"
#define DIALOG_AREAPATHPTDELAY		"Nombre de secondes d'attente avant de rejoindre la prochaine zone"

#define DIALOG_MAPPROPSTITLE		"Propriétés de la carte"
#define DIALOG_MAPPROPSINFO		"Informations de la carte"
#define DIALOG_MAPPROPSNAME		"Nom de la carte"
#define DIALOG_MAPPROPSINFOTEXTS	"Descriptions"
#define DIALOG_MAPPROPSDIM		"Dimensions de la carte"
#define DIALOG_MAPPROPSWIDTH		"Largeur:"
#define DIALOG_MAPPROPSHEIGHT		"Hauteur:"
#define DIALOG_MAPPROPSRESET		"Réinitialiser"
#define DIALOG_MAPPROPSSIZE		"Emplacement de la carte"
#define DIALOG_MAPPROPSKEEPERS		"Propriétés des joueurs"
#define DIALOG_MAPPROPSHEROS		"Héros"
#define DIALOG_MAPPROPSNEUTRAL		"Neutre"
#define DIALOG_MAPPROPSKEEPER1		"Gardien 1"
#define DIALOG_MAPPROPSKEEPER2		"Gardien 2"
#define DIALOG_MAPPROPSKEEPER3		"Gardien 3"
#define DIALOG_MAPPROPSKEEPER4		"Gardien 4"
#define DIALOG_MAPPROPSKEEPER5		"Gardien 5"
#define DIALOG_MAPPROPSALLIES		"Alliances"
#define DIALOG_MAPPROPSCREATURES	"Créatures"
#define DIALOG_MAPPROPSVOICES		"Voix"
#define DIALOG_MAPPROPSTEXTS		"Textes"
#define DIALOG_MAPPROPSVARIABLES	"Variables"
#define DIALOG_MAPPROPSOPTIONS		"Options"

#define DIALOG_MAPPLAYERTITLE		"Propriétés du joueur"
#define DIALOG_MAPPLAYERINFO		"Informations sur le joueur"
#define DIALOG_MAPPLAYERNAME		"Nom"
#define DIALOG_MAPPLAYERCPU		"Ordinateur"
#define DIALOG_MAPPLAYERCPUOPTS		"Paramètres"
#define DIALOG_MAPPLAYERGOLD		"Or au démarrage / Dans tout le niveau"
#define DIALOG_MAPPLAYERTREASURY	"Capacité des salles du trésor"
#define DIALOG_MAPPLAYERCAMERA		"Position de démarrage de la caméra"
#define DIALOG_MAPPLAYERCAMERASELECT	"Sélectionner la position"
#define DIALOG_MAPPLAYERELEMENTS	"Liste des éléments"
#define DIALOG_MAPPLAYEROPTIONS		"Options des élém. sélectionnés"
#define DIALOG_MAPPLAYERNONE		"Ne rien spécifier"
#define DIALOG_MAPPLAYERNA		"Indisponible"
#define DIALOG_MAPPLAYERRESEARCH	"A rechercher"
#define DIALOG_MAPPLAYEROK		"Acquis dès le départ"
#define DIALOG_MAPPLAYERLOCKED		"Bloqué"
#define DIALOG_MAPPLAYERCRLIST		"Liste des créatures"
#define DIALOG_MAPPLAYERCRSELECT	"Créatures sélectionnées"
#define DIALOG_MAPPLAYERCRMAX		"Nombre maximum"
#define DIALOG_MAPPLAYERCRCANT		"Ne rien spécifier"
#define DIALOG_MAPPLAYERDEFAULT		"Par défaut"

#define DIALOG_MAPCPUSECONDS		"seconde(s)"
#define DIALOG_MAPCPUTILES		"carré(s)"
#define DIALOG_MAPCPUCREATURESAMOUNT	"créature(s)"
#define DIALOG_MAPCPUPERCENT		"%"
#define DIALOG_MAPCPU0			"0%"
#define DIALOG_MAPCPU100		"100%"
#define DIALOG_MAPCPUPRESETS		"Définitions"
#define DIALOG_MAPCPUPRESETSLIST	"Liste des définitions"
#define DIALOG_MAPCPUPRESETSUSE		"Utiliser les valeurs par défaut pour cette définition"
#define DIALOG_MAPCPUBUILDS		"Constructions"
#define DIALOG_MAPCPUAREA		"Zone d'expansion"
#define DIALOG_MAPCPUX1			"X1"
#define DIALOG_MAPCPUY1			"Y1"
#define DIALOG_MAPCPUX2			"X2"
#define DIALOG_MAPCPUY2			"Y2"
#define DIALOG_MAPCPUUSEAREA		"Utiliser les coordonnées de la zone..."
#define DIALOG_MAPCPUORDER		"Ordre de construction"
#define DIALOG_MAPCPUROOMS		"Salles"
#define DIALOG_MAPCPUROOMSWAIT		"Temps d'attente avant de construire une salle découverte:"
#define DIALOG_MAPCPUROOMSLOST		"Constuire les salles perdues après"
#define DIALOG_MAPCPUROOMSSIZE		"Taille des salles:"
#define DIALOG_MAPCPUROOMSSPACE		"Nombre de carrés entre chaque salle:"
#define DIALOG_MAPCPUROOMSNEAR		"Distance entre les salles devant être proches:"
#define DIALOG_MAPCPUROOMSCORRIDOR	"Style de couloir:"
#define DIALOG_MAPCPUROOMSEXPAND	"Quand l'espace disponible dans une salle devient insuffisant,"
#define DIALOG_MAPCPUROOMSNEUTRAL1	"Creuser jusqu'aux salles neutres se trouvant à"
#define DIALOG_MAPCPUROOMSNEUTRAL2	"carré(s) du coeur du donjon"
#define DIALOG_MAPCPUROOMSNEUTRAL3	"carré(s) des zones réclamées"
#define DIALOG_MAPCPUROOMSSELL		"Vendre les salles capturées lors des besoins en trésorerie"
#define DIALOG_MAPCPUROOMSFLEXIBILITY	"Flexibilité:"
#define DIALOG_MAPCPUROOMSIDLE		"Créer des zones vides en cas d'inactivité"
#define DIALOG_MAPCPUROOMSEXPANDLAIR	"Créer un antre plus grand après avoir réclamé un portail"
#define DIALOG_MAPCPUDOORSNTRAPS	"Portes && pièges"
#define DIALOG_MAPCPUDTTRAPS		"Le gardien utilisera plutôt des pièges..."
#define DIALOG_MAPCPUDTAGGRESSIVE	"Agressifs"
#define DIALOG_MAPCPUDTDEFENSIVE	"Défensifs"
#define DIALOG_MAPCPUDTPREF		"Le gardien utilisera plus volontier des..."
#define DIALOG_MAPCPUDTTRAP		"Pièges"
#define DIALOG_MAPCPUDTDOOR		"Portes"
#define DIALOG_MAPCPUDTBESTDOOR		"Construire les meilleures portes"
#define DIALOG_MAPCPUDTWORSTDOOR	"Construire les plus mauvaises portes"
#define DIALOG_MAPCPUDTRANDOMDOOR	"Choisir les portes aléatoirement"
#define DIALOG_MAPCPUDTCORRIDOR		"Placer des pièges rocher dans les longs couloirs"
#define DIALOG_MAPCPUDTBREACH		"Placer des pièges rocher dans les couloirs menant aux brèches"
#define DIALOG_MAPCPUDTCHANCE		"Probabilité pour que le gardien construise des portes et des pièges..."
#define DIALOG_MAPCPUSPELLS		"Sorts"
#define DIALOG_MAPCPUBATTLESPELL	"Fréquence d'utilisation des sorts lors des combats:"
#define DIALOG_MAPCPUOFTEN		"Souvent"
#define DIALOG_MAPCPURARELY		"Rarement"
#define DIALOG_MAPCPUSPELLPOWER		"Le gardien utiliser plutôt des sorts..."
#define DIALOG_MAPCPUSPELLHIGHPOWER	"Puissants"
#define DIALOG_MAPCPUSPELLLOPOWER	"Peu puissants"
#define DIALOG_MAPCPUSIGHTOFEVIL	"Utiliser le sort oeil du diable..."
#define DIALOG_MAPCPUCALLTOARMS		"Utiliser le sort ralliement..."
#define DIALOG_MAPCPULIGHTNING		"Utiliser le sort foudre si l'ennemi est sur l'eau"
#define DIALOG_MAPCPUCREATURES		"Créatures"
#define DIALOG_MAPCPUSADTOHAPPY		"Le gardien essaye de rendre heureuses les créatures malheureuses"
#define DIALOG_MAPCPUUNGRYTOHAPPY	"Le gardien essaye de rendre heureuses les créatures furieuses"
#define DIALOG_MAPCPUSACKUNGRY		"Le gardien vire les créatures furieuses"
#define DIALOG_MAPCPUSACKUNUSED		"Le gardien vire les créatures inutiles si de meilleures arrivent"
#define DIALOG_MAPCPUSACKMETHOD		"Le gardien vire ses créatures en les..."
#define DIALOG_MAPCPUIMPSMAX		"Nombre maximum de lutins:"
#define DIALOG_MAPCPUDONTSLAP		"Le gardien ne frappe pas ses créatures"
#define DIALOG_MAPCPUFIRSTBATTLE	"Première attaque"
#define DIALOG_MAPCPUCONDITIONS		"Conditions d'attaque"
#define DIALOG_MAPCPULEVEL		"Toutes les créatures ont atteint le niveau:"
#define DIALOG_MAPCPUOWN		"Le gardien possède au moins"
#define DIALOG_MAPCPUTHREAT		"La menace representée par les créatures est"
#define DIALOG_MAPCPUTHREAT2		"% supérieure à celle de l'ennemi"
#define DIALOG_MAPCPUALLROOMS		"Toutes les salles ont été construites"
#define DIALOG_MAPCPUALLSPELLS		"Tous les sorts ont été trouvés"
#define DIALOG_MAPCPUSTYLE		"Type d'attaque"
#define DIALOG_MAPCPUBREACHTO		"Le gardien essaye d'abord de s'attaquer..."
#define DIALOG_MAPCPUDIGTO		"Le gardien tente de créer une brèche..."
#define DIALOG_MAPCPUCOUNT		"Attaquer par"
#define DIALOG_MAPCPUCOUNT2		"côté(s)"
#define DIALOG_MAPCPUFORCES		"Créatures à utiliser lors de la première attaque:"
#define DIALOG_MAPCPUFORCES2		"% du total"
#define DIALOG_MAPCPUMAINCONDITION	"Comportement général d'attaque"
#define DIALOG_MAPCPUCOUNTERATTACK	"Contre-attaque en cas d'invasion du donjon par l'ennemi"
#define DIALOG_MAPCPUDONTATTACK		"Ne jamais attaquer l'ennemi"
#define DIALOG_MAPCPUBATTLES		"Combats"
#define DIALOG_MAPCPUBTHREAT1		"La menace représentée par les créatures déposées doit correspondre à"
#define DIALOG_MAPCPUBTHREAT2		"% de la menace représentée par l'ennemi"
#define DIALOG_MAPCPUBPELL		"Utiliser des sorts"
#define DIALOG_MAPCPUBJAIL1		"Tenter d'emprisonner"
#define DIALOG_MAPCPUBJAIL2		"% des créatures ennemies"
#define DIALOG_MAPCPUBPULLOUT		"Enlever les créatures de la bataille si l'ennemi est supérieur en nombre et qu'aucun renfort n'est disponible"
#define DIALOG_MAPCPUBHEALTH1		"Si la vitalité de la créature est égale à "
#define DIALOG_MAPCPUBHEALTH2		"% de son total et qu'elle ne se trouve pas sur son terrain, la déplacer dans un antre ou dans un temple"
#define DIALOG_MAPCPUBCALLTOARMS	"Drapeau du ralliement"
#define DIALOG_MAPCPUBCALLTOARMS1	"Le placer là où la menace est supérieure à"
#define DIALOG_MAPCPUBCALLTOARMS2	"Le retirer après"
#define DIALOG_MAPCPUBCALLTOARMS3	"Le retirer si moins de"
#define DIALOG_MAPCPUBCALLTOARMS4	"créatures ennemies se trouvent dans les"
#define DIALOG_MAPCPUBCALLTOARMS5	"carrés alentours"
#define DIALOG_MAPCPUBCALLTOARMS6	"Le retirer s'il reste moins de"
#define DIALOG_MAPCPUBCALLTOARMS7	"créatures disponibles"
#define DIALOG_MAPCPUBATTACKAGAIN	"Attente entre chaque attaque:"
#define DIALOG_MAPCPUOTHER		"Autre"
#define DIALOG_MAPCPUOLIBRARY		"Probabilité d'utilisation de la bibliothèque occulte:"
#define DIALOG_MAPCPUOJAILED		"Sort réservé aux créatures emprisonnées:"
#define DIALOG_MAPCPUOGOLDMINED		"Collecter de l'or jusqu'à ce que le montant soit supérieur à:"
#define DIALOG_MAPCPUOSPECIALS1		"Nombre de carrés à explorer afin de rechercher des secrets:"
#define DIALOG_MAPCPUOSPECIALS2		"Probabilité que le gardien recherche des secrets:"
#define DIALOG_MAPCPUOSPECIALS3		"Probabilité que le gardien trouve des secrets:"
#define DIALOG_MAPCPUORATIO		"Ratio (Carrés/Lutins)-1:"
#define DIALOG_MAPCPUOSTARTINGMANA	"Mana au démarrage:"
#define DIALOG_MAPCPUOSPEED		"Vitesse:"
#define DIALOG_MAPCPUOMANA		"Mana:"
#define DIALOG_MAPCPUOGOLD		"Or:"
#define DIALOG_MAPCPUOOPENNESS		"Taux d'exposition:"

#define DIALOG_MAPALLIESTITLE		"Modification des alliances"
#define DIALOG_MAPALLIES		"Alliances"

#define DIALOG_MAPCREATURESTITLE	"Modification des paramètres des créatures"
#define DIALOG_MAPCREATURES		"Liste des créatures"
#define DIALOG_MAPCREATURESPARAMS	"Paramètres des créatures sélectionnées"
#define DIALOG_MAPCREATURESRES		"Résistance"
#define DIALOG_MAPCREATURESCOR		"Courage"
#define DIALOG_MAPCREATURESCHA		"Charisme"
#define DIALOG_MAPCREATURESSTR		"Force"

#define DIALOG_MAPVOICETITLE		"Voix du jeu"
#define DIALOG_MAPVOICEFILE		"Fichier son"
#define DIALOG_MAPVOICEIDENTIFIERS	"Identificateurs (SPEECH_MENTOR)"
#define DIALOG_MAPVOICEINTROLEVEL	"Introduction du niveau"
#define DIALOG_MAPVOICEVICTORY		"Victoire"
#define DIALOG_MAPVOICEDEFEAT		"Défaite"
#define DIALOG_MAPVOICEENDLEVEL		"Fin de niveau"
#define DIALOG_MAPVOICEGENERIC		"Introduction générique"
#define DIALOG_MAPVOICELIST		"Sons présents dans le fichier son sélectionné"

#define DIALOG_MAPTXTTITLE		"Textes du jeu"
#define DIALOG_MAPTXTFILE		"Fichier texte"
#define DIALOG_MAPTXTINTRO		"Introduction && objectifs (Phases intermédiaires)"
#define DIALOG_MAPTXTINTROTITLE		"Titre"
#define DIALOG_MAPTXTINTROSPOT		"Intrigue"
#define DIALOG_MAPTXTDEBRIEFING		"Debriefing"
#define DIALOG_MAPTXTMAINOBJECTIVE	"Objectif principal"
#define DIALOG_MAPTXTSUBOBJECTIVE1	"Premier objectif secondaire"
#define DIALOG_MAPTXTSUBOBJECTIVE2	"Deuxième objectif secondaire"
#define DIALOG_MAPTXTSUBOBJECTIVE3	"Troisième objectif secondaire"
#define DIALOG_MAPTXTOVERRIDE		"Textes de remplacement lors de l'apparition des créatures"
#define DIALOG_MAPTXTOVERRIDE1		"1:"
#define DIALOG_MAPTXTOVERRIDE2		"2:"
#define DIALOG_MAPTXTOVERRIDE3		"3:"
#define DIALOG_MAPTXTOVERRIDE4		"4:"
#define DIALOG_MAPTXTOVERRIDE5		"5:"
#define DIALOG_MAPTXTOVERRIDE6		"6:"
#define DIALOG_MAPTXTOVERRIDE7		"7:"
#define DIALOG_MAPTXTOVERRIDE8		"8:"
#define DIALOG_MAPTXTLIST		"Liste des textes"

#define DIALOG_MAPVARSTITLE		"Modification des variables du jeu"
#define DIALOG_MAPVARSLIST		"Variables"
#define DIALOG_MAPVARSMODIFY		"Modifier"
#define DIALOG_MAPVARSDEFAULT		"Par défaut"

#define DIALOG_MAPOPTIONSTITLE		"Options du niveau"
#define DIALOG_MAPOPTIONSGAME		"Divers"
#define DIALOG_MAPOPTIONSHORNY		"Nombre de pièces acquises du talisman d'Horny"
#define DIALOG_MAPOPTIONSSPEED		"Vitesse du jeu"
#define DIALOG_MAPOPTIONSTRACK		"Piste audio"
#define DIALOG_MAPOPTIONSTYPE		"Type de niveau"
#define DIALOG_MAPOPTIONSSECRET		"Niveau secret"
#define DIALOG_MAPOPTIONSSPECIAL	"Niveau spécial"
#define DIALOG_MAPOPTIONSMULTI		"Niveau jouable en multi-joueurs"
#define DIALOG_MAPOPTIONSSINGLE		"Niveau jouable en mode escarmouche"
#define DIALOG_MAPOPTIONSPETDONJON	"P'tit donjon"
#define DIALOG_MAPOPTIONSPARAMS		"Paramètres"
#define DIALOG_MAPOPTIONSJAIL		"Toujours emprisonner les ennemis"
#define DIALOG_MAPOPTIONSCRYSTAL	"Le dernier donjon détruit génère un cristal"
#define DIALOG_MAPOPTIONSHORNYONE	"N'autoriser qu'une seule utilisation du grand cornu"
#define DIALOG_MAPOPTIONSOBJECTIVES	"Afficher les objectifs au démarrage"
#define DIALOG_MAPOPTIONSLOCKOPTIONS	"Bloquer les options du jeu"
#define DIALOG_MAPOPTIONSLOCKPOSSESS	"Empêcher l'arrêt de la possession"
#define DIALOG_MAPOPTIONSKILLEDHEROES	"Afficher le nombre de héros tués"
#define DIALOG_MAPOPTIONSREWARDS	"Récompenses"

#define DIALOG_MAPGBLDEFAULT		"Par défaut"
#define DIALOG_MAPGBLDEFAULTALL		"Tout par défaut"
#define DIALOG_MAPGBLTERRAINS		"Terrains"
#define DIALOG_MAPGBLTNAMES		"Terrains modifiables"
#define DIALOG_MAPGBLTMAXHEALTH		"Quand l'energie est à son maximum"
#define DIALOG_MAPGBLTDESTROYED		"Quand le terrain est détruit"
#define DIALOG_MAPGBLTBECOME		"Devient"
#define DIALOG_MAPGBLTEFFECT		"Effet"
#define DIALOG_MAPGBLTOPTIONS		"Paramètres"
#define DIALOG_MAPGBLTDAMAGE		"Modification de la santé des créatures"
#define DIALOG_MAPGBLTGOLD		"Quantité d'or contenue dans le terrain"
#define DIALOG_MAPGBLTHEALTHMAX		"Energie max."
#define DIALOG_MAPGBLTHEALTH		"Energie de départ"
#define DIALOG_MAPGBLTMANA		"Quantité de mana généré par le terrain"
#define DIALOG_MAPGBLTMANAMAX		"Mana max."
#define DIALOG_MAPGBLTWIBBLEH		"Déformation horizontale"
#define DIALOG_MAPGBLTWIBBLEV		"Verticale"
#define DIALOG_MAPGBLTVISIBLE		"Visible à travers le champ de perception"
#define DIALOG_MAPGBLTLIGHTS		"Lumières"
#define DIALOG_MAPGBLTTERRAINLIGHT	"Lumière générée par le terrain"
#define DIALOG_MAPGBLTAMBIANTLIGHT	"Lumière ambiante"
#define DIALOG_MAPGBLTLIGHTHEIGHT	"Hauteur de la lumière du terrain"
#define DIALOG_MAPGBLROOMS		"Salles"
#define DIALOG_MAPGBLRNAMES		"Salles modifiables"
#define DIALOG_MAPGBLREFFECTS		"Effets pouvant se produire dans cette salle"
#define DIALOG_MAPGBLROBJECTS		"Objets pouvant se trouver dans cette salle"
#define DIALOG_MAPGBLRFIGHTEFFECT	"En combat:"
#define DIALOG_MAPGBLR0			"0:"
#define DIALOG_MAPGBLR1			"1:"
#define DIALOG_MAPGBLR2			"2:"
#define DIALOG_MAPGBLR3			"3:"
#define DIALOG_MAPGBLR4			"4:"
#define DIALOG_MAPGBLR5			"5:"
#define DIALOG_MAPGBLRPARAMS		"Paramètres"
#define DIALOG_MAPGBLRCOST		"Coût d'un carré de salle"
#define DIALOG_MAPGBLRLIGHT		"Lumière des torches"
#define DIALOG_MAPGBLRINTENSITY		"Intensité"
#define DIALOG_MAPGBLRHEIGHT		"Hauteur"
#define DIALOG_MAPGBLRRADIUS		"Rayon"
#define DIALOG_MAPGBLDOORS		"Portes"
#define DIALOG_MAPGBLDNAMES		"Portes modifiables"
#define DIALOG_MAPGBLDMATERIAL		"Options relatives au matériel"
#define DIALOG_MAPGBLDMATERIALTYPE	"Type de matériel"
#define DIALOG_MAPGBLDDEATHEFFECT	"Effet lors de la destruction"
#define DIALOG_MAPGBLDCRATE		"Coffre"
#define DIALOG_MAPGBLDKEY		"Serrure"
#define DIALOG_MAPGBLDCOST		"Coût en or"
#define DIALOG_MAPGBLDBUILD		"Points de fabrication"
#define DIALOG_MAPGBLDHEALTH		"Energie"
#define DIALOG_MAPGBLDHEALTHGAIN	"Régénération"
#define DIALOG_MAPGBLDMANACOST		"Coût en mana"
#define DIALOG_MAPGBLDPARAMS		"Paramètres"
#define DIALOG_MAPGBLTRAPS		"Pièges"
#define DIALOG_MAPGBLANAMES		"Pièges modifiables"
#define DIALOG_MAPGBLAEFFECTS		"Effets"
#define DIALOG_MAPGBLADEATH		"Destruction"
#define DIALOG_MAPGBLAMANA		"Pas de mana"
#define DIALOG_MAPGBLAIDLE		"Inactif"
#define DIALOG_MAPGBLAIDLEDELAY		"Intervalle entre chaque déclenchement de l'effet inactif"
#define DIALOG_MAPGBLAFLAGS		"Drapeaux"
#define DIALOG_MAPGBLAINVISIBLE		"Invisible"
#define DIALOG_MAPGBLADISARMABLE	"Peut être désarmé"
#define DIALOG_MAPGBLAREVEAL		"Apparaît après déclenchement"
#define DIALOG_MAPGBLAUSEMANA		"Nécessite du mana"
#define DIALOG_MAPGBLASOLIDOBSTACLE	"Obstacle solide"
#define DIALOG_MAPGBLAFPSOLID		"Obstacle solide (possession)"
#define DIALOG_MAPGBLAPARAMS		"Paramètres"
#define DIALOG_MAPGBLAHEALTH		"Energie"
#define DIALOG_MAPGBLAHEALTHGAIN	"Régénération"
#define DIALOG_MAPGBLACHARGETIME	"Temps de chargement"
#define DIALOG_MAPGBLARECHARGETIME	"Temps pour recharger"
#define DIALOG_MAPGBLAGOLDCOST		"Coût en or"
#define DIALOG_MAPGBLAMANACOST		"Coût en mana"
#define DIALOG_MAPGBLAMANACOSTTOFIRE	"Mana pour tirer"
#define DIALOG_MAPGBLAMANAUSAGE		"Mana utilisé"
#define DIALOG_MAPGBLATHREAT		"Menace"
#define DIALOG_MAPGBLATHREATDURATION	"Durée de la menace"
#define DIALOG_MAPGBLATRIGGER		"Type d'activation"
#define DIALOG_MAPGBLASHOT		"Type de sort"
#define DIALOG_MAPGBLAOPT		"?"
#define DIALOG_MAPGBLSPELLS		"Sorts"
#define DIALOG_MAPGBLSNAMES		"Sorts modifiables"
#define DIALOG_MAPGBLSCURSOR		"Curseur"
#define DIALOG_MAPGBLSOK		"Par défaut"
#define DIALOG_MAPGBLSNOGO		"Lancement impossible"
#define DIALOG_MAPGBLSRULES		"Règles d'utilisation"
#define DIALOG_MAPGBLSCAST		"Lancement"
#define DIALOG_MAPGBLSTARGET		"Cible"
#define DIALOG_MAPGBLSPARAMS		"Paramètres"
#define DIALOG_MAPGBLSMANACOST		"Coût en mana"
#define DIALOG_MAPGBLSMANADRAIN		"Montant de mana utilisé"
#define DIALOG_MAPGBLSRECHARGETIME	"Délai avant prochaine utilisation"
#define DIALOG_MAPGBLSBONUSTIME		"Bonus de temps après amélioration"
#define DIALOG_MAPGBLSATTACKING		"Sort d'attaque"
#define DIALOG_MAPGBLSDEFENSIVE		"Sort de défense"
#define DIALOG_MAPGBLSSHOTS		"Sorts"
#define DIALOG_MAPGBLSTYPE		"Normal"
#define DIALOG_MAPGBLSUPGRADE		"Amélioré"
#define DIALOG_MAPGBLOPTIONSTYPE	"Paramètres de l'activation"
#define DIALOG_MAPGBLOPTIONSSHOTS	"Paramètres du sort"
#define DIALOG_MAPGBLOPTIONS1		"Première donnée"
#define DIALOG_MAPGBLOPTIONS2		"Deuxième donnée"
#define DIALOG_MAPGBLOPTIONSCR		"Sélectionnez une créature"
#define DIALOG_MAPGBLOPTIONSOB		"Sélectionnez un objet"
#define DIALOG_MAPGBLOPTIONSCOUNT	"Nombre de créatures"
#define DIALOG_MAPGBLOPTIONSLEVEL	"Niveau de la créature"
#define DIALOG_MAPGBLOPTIONSGOLD	"Quantité d'or"

#define DIALOG_MAPGCREATURES		"Créatures disponibles"
#define DIALOG_MAPGCRATTRIBUTES		"Attributs"
#define DIALOG_MAPGCRATTRLIST		"Liste des attributs"
#define DIALOG_MAPGCRATTRDEFAULT	"Valeur par défaut"
#define DIALOG_MAPGCRATTRVALUE		"Nouvelle valeur"
#define DIALOG_MAPGCRPARAMS		"Paramètres"
#define DIALOG_MAPGCRPARAMSTYPES	"Types"
#define DIALOG_MAPGCRPARAMSARMOUR	"Armure"
#define DIALOG_MAPGCRPARAMSFIGHT	"Style de combattant"
#define DIALOG_MAPGCRPARAMSCLASS	"Catégorie"
#define DIALOG_MAPGCRPARAMSBED		"Lit"
#define DIALOG_MAPGCRPARAMSEFFECTS	"Effets"
#define DIALOG_MAPGCRPARAMSSLAP		"Lors d'un coup"
#define DIALOG_MAPGCRPARAMSHEALTH	"Lors d'une régénération"
#define DIALOG_MAPGCRPARAMSENTRANCE	"Lors de l'entrée par un portail"
#define DIALOG_MAPGCRPARAMSDEATH	"Lors de la mort"
#define DIALOG_MAPGCRPARAMSATTRACT	"Cette créature est attirée..."
#define DIALOG_MAPGCRPARAMSATTRACT1	"...par..."
#define DIALOG_MAPGCRPARAMSATTRACT2	"...et..."
#define DIALOG_MAPGCRFLAGS		"Drapeaux"
#define DIALOG_MAPGCRFLAG00		"S'entraîne en cas d'inaction"
#define DIALOG_MAPGCRFLAG01		"Peut être attrappée"
#define DIALOG_MAPGCRFLAG02		"Peut être frappée"
#define DIALOG_MAPGCRFLAG03		"Peut marcher sur l'eau"
#define DIALOG_MAPGCRFLAG04		"Peut marcher sur la lave"
#define DIALOG_MAPGCRFLAG05		"Peut être hypnotisée"
#define DIALOG_MAPGCRFLAG06		"Immunisée contre le sort endoctrinement"
#define DIALOG_MAPGCRFLAG07		"Immunisée contre le sort galinamorphose"
#define DIALOG_MAPGCRFLAG08		"Immunisée contre la foudre"
#define DIALOG_MAPGCRFLAG09		"Génère un cadavre en cas de décès"
#define DIALOG_MAPGCRFLAG10		"Ne se fâche pas avec les créatures ennemies"
#define DIALOG_MAPGCRFLAG11		"Libère ses alliés en cas d'évasion"
#define DIALOG_MAPGCRFLAG12		"Fait apparaître les pièges aux alentours"
#define DIALOG_MAPGCRFLAG13		"N'a peur de rien"
#define DIALOG_MAPGCRFLAG14		"Ne ressent aucune émotion"
#define DIALOG_MAPGCRFLAG15		"Utiliser cette créature dans les bandes de héros aléatoires"
#define DIALOG_MAPGCRATTACKS		"Attaques"
#define DIALOG_MAPGCRATTACKSHOTS	"Sorts"
#define DIALOG_MAPGCRATTACKSHOT1	"Premier"
#define DIALOG_MAPGCRATTACKSHOT2	"Deuxième"
#define DIALOG_MAPGCRATTACKSHOT3	"Troisième"
#define DIALOG_MAPGCRATTACKSHOTDELAY	"Délai"
#define DIALOG_MAPGCRATTACKSHOTLEVEL	"Dispo. au niveau"
#define DIALOG_MAPGCRATTACKSHOTX	"Offset X"
#define DIALOG_MAPGCRATTACKSHOTY	"Offset Y"
#define DIALOG_MAPGCRATTACKSHOTZ	"Offset Z"
#define DIALOG_MAPGCRATTACKMELEE	"Corps-à-corps"
#define DIALOG_MAPGCRATTACKMELEETYPE	"Type d'arme"
#define DIALOG_MAPGCRATTACKMELEETIME	"Temps pour recharger"
#define DIALOG_MAPGCRATTACKMELEERANGE	"Portée du coup"
#define DIALOG_MAPGCRATTACKMELEEDMG	"Puissance du coup"
#define DIALOG_MAPGCRATTACKMELEEDELAY	"Délai"
#define DIALOG_MAPGCRRESISTANCES	"Résistances"
#define DIALOG_MAPGCRRESISTANCE1	"Résiste à..."
#define DIALOG_MAPGCRRESISTANCE2	"...et à..."
#define DIALOG_MAPGCRRESISTANCE0PC	"0%"
#define DIALOG_MAPGCRRESISTANCE100PC	"100%"
#define DIALOG_MAPGCRPOSSESSION		"Possession"
#define DIALOG_MAPGCR1STSPECIALS	"Capacités spéciales"
#define DIALOG_MAPGCR1STSPECIAL1	"Capacité 1"
#define DIALOG_MAPGCR1STSPECIAL2	"Capacité 2"
#define DIALOG_MAPGCR1STSWIPE		"Coups"
#define DIALOG_MAPGCR1STSWIPEMELEE1	"Corps-à-corps 1"
#define DIALOG_MAPGCR1STSWIPEMELEE2	"Corps-à-corps 2"
#define DIALOG_MAPGCR1STSWIPESPECIAL1	"Spécial 1"
#define DIALOG_MAPGCR1STSWIPESPECIAL2	"Spécial 2"
#define DIALOG_MAPGCR1STSWIPESPELL	"Sort"
#define DIALOG_MAPGCR1STMOVEMENT	"Vue & Mouvements"
#define DIALOG_MAPGCR1STGAMMA		"Filtre visuel"
#define DIALOG_MAPGCR1STWADDLE		"Dandinement"
#define DIALOG_MAPGCR1STOSCILLATE	"Oscillation"
#define DIALOG_MAPGCR1STWALK		"Cycle de marche"
#define DIALOG_MAPGCR1STCAMERA		"La caméra roule lorsque la créature tourne"
#define DIALOG_MAPGCRJOBS		"Occupations"
#define DIALOG_MAPGCRJOBHAPPY		"Occupations lorsque la créature est heureuse"
#define DIALOG_MAPGCRJOBUNHAPPY		"Occupations lorsque la créature est malheureuse"
#define DIALOG_MAPGCRJOBANGRY		"Occupations lorsque la créature est furieuse"
#define DIALOG_MAPGCRJOBHATE		"Occupations que la créature déteste"
#define DIALOG_MAPGCRJOBCHANCE		"Chance"
#define DIALOG_MAPGCRJOBMOOD		"Humeur"
#define DIALOG_MAPGCRJOBMANA		"Mana"
#define DIALOG_MAPGCRJOBADD		">>"
#define DIALOG_MAPGCRJOBREM		"<<"
#define DIALOG_MAPGCRLIGHT		"Lumière"
#define DIALOG_MAPGCRLIGHTPOS		"Positionnement"
#define DIALOG_MAPGCRLIGHTX		"Axe X"
#define DIALOG_MAPGCRLIGHTY		"Axe Y"
#define DIALOG_MAPGCRLIGHTZ		"Axe Z"
#define DIALOG_MAPGCRLIGHTPARAMS	"Paramètres"
#define DIALOG_MAPGCRLIGHTRADIUS	"Rayon"
#define DIALOG_MAPGCRLIGHTRGB		"Couleur"
#define DIALOG_MAPGCRLIGHTFLAGS		"Drapeaux"
#define DIALOG_MAPGCRLIGHTFLICKER	"Scintille"
#define DIALOG_MAPGCRLIGHTPULSE		"Emet des pulsations"
#define DIALOG_MAPGCRLIGHTPLAYER	"Même couleur que le joueur"
#define DIALOG_MAPGCRSPELLS		"Sorts"
#define DIALOG_MAPGCRSPELLSLIST		"Sorts disponibles"
#define DIALOG_MAPGCRSPELLPARAMS	"Paramètres"
#define DIALOG_MAPGCRSPELLTIME		"Temps pour recharger"
#define DIALOG_MAPGCRSPELLRANGE		"Portée"
#define DIALOG_MAPGCRSPELLSHOT		"Type de sort"
#define DIALOG_MAPGCRSPELLFLAGS		"Drapeaux"
#define DIALOG_MAPGCRSPELLATTACK	"Sort d'attaque"
#define DIALOG_MAPGCRSPELLDEFENSIVE	"Sort de défense"
#define DIALOG_MAPGCRSPELLCREATURE	"Sort de créature"
#define DIALOG_MAPGCRSPELLCASTONSELF	"La créature utilise ce sort sur elle"
#define DIALOG_MAPGCRSPELLCASTONOTHERS	"La créature utilise ce sort sur les autres"
#define DIALOG_MAPGCRSPELLCREATURES	"Ce sort ne s'utilise que sur les créatures"
#define DIALOG_MAPGCRSPELLUSEDBY	"Créatures utilisant ce sort"

#define DIALOG_NEWTITLE			"Nouvelle carte..."
#define DIALOG_NEWVERSION		"Version"
#define DIALOG_NEWPLAYERS		"Joueurs"
#define DIALOG_NEWMAPNAME		"Nom de la carte"
#define DIALOG_NEWSIZE			"Dimensions"
#define DIALOG_NEWWIDTH			"Largeur:"
#define DIALOG_NEWHEIGHT		"Hauteur:"
#define DIALOG_NEWSQUARE		"Carte carrée"
#define DIALOG_NEWFILLWITH		"Remplir la carte avec..."

#define DIALOG_STATSEDITTITLE		"Edition"
#define DIALOG_STATSEDIT		"Carte"
#define DIALOG_STATSEDITTIME		"Temps total d'édition (JJ/HH:MM:SS)"
#define DIALOG_STATSLMB			"Nombre de clicks gauches effectués"
#define DIALOG_STATSRMB			"Nombre de clicks droits effectués"
#define DIALOG_STATSUNDO		"Nombre d'annulation effectuées"
#define DIALOG_STATSPAINT		"Détail des opérations réalisées"
#define DIALOG_STATSPAINTTHINGS		"Nombre d'objets posés"
#define DIALOG_STATSPAINTFILL		"Nombre de remplissages effectuées"
#define DIALOG_STATSPAINTMODE		"Nombre de formes réalisées"
#define DIALOG_STATSPAINTRNDMODE	"Nombre de formes aléatoires réalisées"
#define DIALOG_STATSFILES		"Fichiers"
#define DIALOG_STATSSAVECOUNT		"Nombre de sauvegardes effectuées"
#define DIALOG_STATSCREATEDTIME		"Création de la carte"
#define DIALOG_STATSCOMPILETIME		"Dernière compilation avant la sauvegarde"
#define DIALOG_STATSLASTSAVE		"Dernière sauvegarde effectuée"
#define DIALOG_STATSMAPTITLE		"Carte"
#define DIALOG_STATSMAPELEMS		"Elements"
#define DIALOG_STATSMAPCREATURES	"Nombre de créatures -- La plus utilisée"
#define DIALOG_STATSMAPLVLCREATURE	"Niveau moyen des créatures"
#define DIALOG_STATSMAPTRAPS		"Nombre de pièges -- Le plus utilisé"
#define DIALOG_STATSMAPDOORS		"Nombre de portes -- La plus utilisée"
#define DIALOG_STATSMAPOBJECTS		"Nombre d'objets -- Le plus utilisé"
#define DIALOG_STATSMAPMAGICS		"Nombre d'objets magiques -- Le plus utilisé"
#define DIALOG_STATSMAPTERRAIN		"Terrains"
#define DIALOG_STATSMAPTOTAL		"Nombre de carrés dans la carte"
#define DIALOG_STATSMAPWATER		"Carrés d'eau"
#define DIALOG_STATSMAPLAVA		"Carrés de lave"
#define DIALOG_STATSMAPSOLID		"Carrés de roche impénétrable"
#define DIALOG_STATSMAPROCK		"Carrés de roche tendre"
#define DIALOG_STATSMAPUNCLAIMED	"Carrés de terre non réclamée"
#define DIALOG_STATSMAPREL		"% du total"
#define DIALOG_STATSMAPGOLD		"Or"
#define DIALOG_STATSMAPTOTALGOLD	"Or dans tout le niveau"
#define DIALOG_STATSMAPOBJECTSGOLD	"Or contenu dans les objets"
#define DIALOG_STATSMAPMAGICSGOLD	"Or contenu dans les objets magiques"
#define DIALOG_STATSMAPGEMS		"Le niveau contient des gems"
#define DIALOG_STATSPLAYERSTITLE	"Joueurs"
#define DIALOG_STATSPLYIMPS		"Nombre de lutins"
#define DIALOG_STATSPLYBUILDINGS	"Constructions"
#define DIALOG_STATSPLYHEART		"Position du coeur du donjon"
#define DIALOG_STATSPLYGOLD		"Capacité des salles du trésor"
#define DIALOG_STATSPLYROOM		"Capacité des antres"
#define DIALOG_STATSPLYMANA		"Régénération en mana"
#define DIALOG_STATSPLYWALLS		"Nombre de murs consolidés"
#define DIALOG_STATSPLYCLAIMED		"Nombre de carrés réclamés"
#define DIALOG_STATSBANDSTITLE		"Bandes de héros"
#define DIALOG_STATSBANDSHEROES		"Statistiques des héros avec les bandes de héros"
#define DIALOG_STATSBANDSALL		"Statistiques de toutes les bandes de héros"
#define DIALOG_STATSBANDSCREATURES	"Nombre de créatures"
#define DIALOG_STATSBANDSDWARFS		"Nombre de nains piocheurs"
#define DIALOG_STATSBANDS		"Statistiques par bande"
#define DIALOG_STATSBANDSLEVELS		"Les nains et les lutins sont inclus dans le calcul"
#define DIALOG_STATSBANDUSECOUNT	"Nombre d'utilisations"

#define DIALOG_TRIGGERS			"Evènements..."
#define DIALOG_TRIGGERSOWNER		"Points d'action"
#define DIALOG_TRIGGERSLIST		"Liste des conditions et actions"
#define DIALOG_TRIGGERSADD		"Ajouter"
#define DIALOG_TRIGGERSINS		"Insérer"
#define DIALOG_TRIGGERSMOD		"Modifier"
#define DIALOG_TRIGGERSDEL		"Supprimer"
#define DIALOG_TRIGGERSADDROOT		"Ajouter à la racine"
#define DIALOG_TRIGGERSTRIGGER		"Déclencheur"
#define DIALOG_TRIGGERSACTION		"Action"
#define DIALOG_TRIGGERSSELECTION	"Sélection"
#define DIALOG_TRIGGERSVARIABLES	"Variables && compteurs"
#define DIALOG_TRIGGERSVRVARLIST	"Liste des variables"
#define DIALOG_TRIGGERSVRTIMLIST	"Liste des compteurs"
#define DIALOG_TRIGGERSVRNAME		"Changer le nom"
#define DIALOG_TRIGGERSPTTITLE		"Points d'action..."
#define DIALOG_TRIGGERSPTLIST		"Sélectionnez le type de point d'action"
#define DIALOG_TRIGGERSPTLEVEL		"Niveau"
#define DIALOG_TRIGGERSPTKEEPER		"Gardien"
#define DIALOG_TRIGGERSPTCREATURE	"Créature"
#define DIALOG_TRIGGERSPTDOOR		"Porte"
#define DIALOG_TRIGGERSPTOBJECT		"Objet"
#define DIALOG_TRIGGERSPTMAGIC		"Objet magique"
#define DIALOG_TRIGGERSPTAREA		"Zone"
#define DIALOG_TRIGGERSPTBAND		"Bande de héros"
#define DIALOG_TRIGGERSPTBANDCREATURE	"Créature dans une bande de héros"
#define DIALOG_TRIGGERSPTPLAYERS	"Sélectionnez le joueur concerné"
#define DIALOG_TRIGGERSPTPLYLIST	"Liste des joueurs"
#define DIALOG_TRIGGERSPTCREATURES	"Sélectionnez la créature concernée"
#define DIALOG_TRIGGERSPTCREATURESLIST	"Liste des créatures"
#define DIALOG_TRIGGERSPTDOORS		"Sélectionnez la porte concernée"
#define DIALOG_TRIGGERSPTDOORSLIST	"Liste des portes"
#define DIALOG_TRIGGERSPTOBJECTS	"Sélectionnez l'objet concerné"
#define DIALOG_TRIGGERSPTOBJECTSLIST	"Liste des objets"
#define DIALOG_TRIGGERSPTMAGICS		"Sélectionnez l'objet magique concerné"
#define DIALOG_TRIGGERSPTMAGICSLIST	"Liste des objets magiques"
#define DIALOG_TRIGGERSPTAREAS		"Sélectionnez la zone concernée"
#define DIALOG_TRIGGERSPTAREASLIST	"Liste des zones"
#define DIALOG_TRIGGERSPTBANDS		"Sélectionnez la bande de héros concernée"
#define DIALOG_TRIGGERSPTBANDSLIST	"Liste des bandes de héros"
#define DIALOG_TRIGGERSTITLE		"Déclencheurs..."
#define DIALOG_TRIGGERSTYPETITLE	"Sélectionnez le type de déclencheur"
#define DIALOG_TRIGGERSTYPELIST		"Liste des déclencheurs"
#define DIALOG_TRIGGERSVARTITLE		"Test d'une variable"
#define DIALOG_TRIGGERSVARLO		"Inférieure à"
#define DIALOG_TRIGGERSVARLS		"Inférieure ou égale à"
#define DIALOG_TRIGGERSVAREQ		"Egale à"
#define DIALOG_TRIGGERSVARHI		"Supérieure à"
#define DIALOG_TRIGGERSVARHS		"Supérieure ou égale à"
#define DIALOG_TRIGGERSVARNE		"Différente de"
#define DIALOG_TRIGGERSTIMERTITLE	"Test d'un compteur"
#define DIALOG_TRIGGERSTIMERLO		"Inférieur à"
#define DIALOG_TRIGGERSTIMERLS		"Inférieur ou égal à"
#define DIALOG_TRIGGERSTIMEREQ		"Egal à"
#define DIALOG_TRIGGERSTIMERHI		"Supérieur à"
#define DIALOG_TRIGGERSTIMERHS		"Supérieur ou égal à"
#define DIALOG_TRIGGERSTIMERNE		"Différent de"
#define DIALOG_TRIGGERSTIMERSECS	"Secs"
#define DIALOG_TRIGGERSRTTYPE		"Comptabiliser..."
#define DIALOG_TRIGGERSRTBLUEPRINTS	"Les esquisses"
#define DIALOG_TRIGGERSRTBUILDS		"Les constructions"
#define DIALOG_TRIGGERSRTALL		"Tout"
#define DIALOG_TRIGGERSELAPSEDTITLE	"Temps écoulé depuis le début du jeu"
#define DIALOG_TRIGGERSELAPSEDTEXT	"Nombre de secondes écoulées (en secondes du jeu)"
#define DIALOG_TRIGGERSTIMETEXT		"Temps (HH:MM:SS)"
#define DIALOG_TRIGGERSCREATURES	"Nombre de créatures possédées par le joueur"
#define DIALOG_TRIGGERSCREATURESTYPE	"Liste des créatures"
#define DIALOG_TRIGGERSCREATURESELITE	"Note: Les élites ne sont pas comptabilisées"
#define DIALOG_TRIGGERSCREATURESCOUNT	"Le joueur doit en possèder..."
#define DIALOG_TRIGGERSCREATURESLO	"Moins de"
#define DIALOG_TRIGGERSCREATURESLS	"Au maximum"
#define DIALOG_TRIGGERSCREATURESEQ	"Un nombre égal à"
#define DIALOG_TRIGGERSCREATURESHI	"Plus de"
#define DIALOG_TRIGGERSCREATURESHS	"Au moins"
#define DIALOG_TRIGGERSCREATURESNE	"Un nombre différent de"
#define DIALOG_TRIGGERSHAPPYCREATURES	"Nombre de créatures heureuses possédées par le joueur"
#define DIALOG_TRIGGERSANGRYCREATURES	"Nombre de créatures furieuses possédées par le joueur"
#define DIALOG_TRIGGERSLOSTCREATURES	"Nombre de créatures perdues par le joueur"
#define DIALOG_TRIGGERSLOSTCOUNT	"Le joueur doit en perdre..."
#define DIALOG_TRIGGERSLOSTKILLBY	"Responsable de la mort des créatures"
#define DIALOG_TRIGGERSKILLEDCREATURES	"Nombre de créatures tuées par le joueur"
#define DIALOG_TRIGGERSKILLEDCOUNT	"Le joueur doit en tuer..."
#define DIALOG_TRIGGERSKILLEDOWNER	"Détenteur des créatures tuées"
#define DIALOG_TRIGGERSLEVELCREATURES	"Niveau atteind par les créatures du joueur"
#define DIALOG_TRIGGERSLEVELCOUNT	"Nombre de créatures devant atteindre ce niveau..."
#define DIALOG_TRIGGERSLEVELTEXT	"Niveau à atteindre"
#define DIALOG_TRIGGERSLEVELNOTE	"Note: Les lutins ne sont pas inclus"
#define DIALOG_TRIGGERSSQUARES		"Nombre de carrés de salles possédés par le joueur"
#define DIALOG_TRIGGERSROOMSSIZE	"Nombre de carrés par salles"
#define DIALOG_TRIGGERSROOMSCONTENT	"Nombre d'objets dans les salles"
#define DIALOG_TRIGGERSROOMSTYPE	"Liste des salles"
#define DIALOG_TRIGGERSROOMSSQUARES	"Carrés utilisés par la salle..."
#define DIALOG_TRIGGERSROOMSOBJECTS	"La salle doit en contenir..."
#define DIALOG_TRIGGERSROOMS		"Nombre de salles possédées par le joueur"
#define DIALOG_TRIGGERSDOORS		"Nombre de portes possédées par le joueur"
#define DIALOG_TRIGGERSDOORSTYPE	"Liste des portes"
#define DIALOG_TRIGGERSDESTROYED	"Nombre de portes et de pièges détruits par le joueur"
#define DIALOG_TRIGGERSDESTROYEDTYPE	"Liste des portes et des pièges"
#define DIALOG_TRIGGERSDESTROYEDCOUNT	"Le joueur doit en détruire..."
#define DIALOG_TRIGGERSTRAPS		"Nombre de pièges possédés par le joueur"
#define DIALOG_TRIGGERSTRAPSTYPE	"Liste des pièges"
#define DIALOG_TRIGGERSSPELLS		"Sort découvert par le joueur"
#define DIALOG_TRIGGERSSPELLSTYPE	"Liste des sorts"
#define DIALOG_TRIGGERSGOLDMINED	"Montant d'or collecté par le joueur"
#define DIALOG_TRIGGERSGOLDTEXT		"Montant d'or"
#define DIALOG_TRIGGERSGOLDAMOUNT	"Montant d'or détenu par le joueur"
#define DIALOG_TRIGGERSMANAAMOUNT	"Montant de mana à disposition du joueur"
#define DIALOG_TRIGGERSMANATEXT		"Montant de mana"
#define DIALOG_TRIGGERSSLAP		"Nombre de coups donnés par le joueur"
#define DIALOG_TRIGGERSSLAPCOUNT	"Nombre de coups que le joueur doit donner..."
#define DIALOG_TRIGGERSINTERFACE	"Le joueur appuie sur un bouton de l'interface"
#define DIALOG_TRIGGERSBUTTONS		"Liste des boutons"
#define DIALOG_TRIGGERSPOSSESS		"Groupe de créatures lors de l'utilisation du sort possession"
#define DIALOG_TRIGGERSPOSSESSCOUNT	"Nombre de créatures à regrouper..."
#define DIALOG_TRIGGERSHEART		"Coeur du donjon détruit"
#define DIALOG_TRIGGERSHEARTTEXT	"Responsable de la destruction"
#define DIALOG_TRIGGERSDEATHS		"Nombre de morts dans une bande de héros"
#define DIALOG_TRIGGERSHEROSBANDS	"Liste des bandes de héros"
#define DIALOG_TRIGGERSBANDCREATED	"Création d'une bande de héros"
#define DIALOG_TRIGGERSDEATHSCOUNT	"Nombre de créatures devant être tuées..."
#define DIALOG_TRIGGERSSTUNNED		"Nombre de créatures assomées dans une bande de héros"
#define DIALOG_TRIGGERSSTUNNEDCOUNT	"Nombre de créatures devant être assommées..."
#define DIALOG_TRIGGERSJAILED		"Nombre de prisonniers dans une bande de héros"
#define DIALOG_TRIGGERSJAILEDCOUNT	"Nombre de créatures devant être prisonnières..."
#define DIALOG_TRIGGERSHURTED		"Vitalité de la créature"
#define DIALOG_TRIGGERSVITALITY		"Le pourcentage de vitalité restant doit être..."
#define DIALOG_TRIGGERSPERCENT		"%"
#define DIALOG_TRIGGERSENTERAREAPS	"Un joueur est dans la zone avec une créature en possession"
#define DIALOG_TRIGGERSENTERAREAPSTEXT	"Liste des joueurs"
#define DIALOG_TRIGGERSENTERAREACP	"Des créatures sont dans la zone"
#define DIALOG_TRIGGERSENTERAREACPCT	"Nombre de créatures devant être dans la zone..."
#define DIALOG_TRIGGERSENTERAREACPPL	"Joueur à qui appartiennent les créatures"
#define DIALOG_TRIGGERSCLAIMAREA	"Un joueur a réclamé des carrés dans la zone"
#define DIALOG_TRIGGERSCLAIMAREAPL	"Joueur qui doit réclamer la zone"
#define DIALOG_TRIGGERSCLAIMAREACT	"Nombre de carrés que le joueur doit réclamer..."
#define DIALOG_TRIGGERSCLAIMALLAREA	"Un joueur réclame toute la zone"
#define DIALOG_TRIGGERSCLAIMALLAREATXT	"Joueur ayant réclamé la zone"
#define DIALOG_TRIGGERSAREACONTENT	"Contenu de la zone"
#define DIALOG_TRIGGERSAREACONTENTTR	"Terrain contenu dans la zone"
#define DIALOG_TRIGGERSAREACONTENTCT	"Nombre de carrés devant contenir ce terrain..."
#define DIALOG_TRIGGERSMAPOWNER		"Joueur devant détenir le terrain"
#define DIALOG_TRIGGERSSELECTAREA	"Un joueur sélectionne la zone"
#define DIALOG_TRIGGERSSELECTAREAPL	"Joueur devant sélectionner la zone"
#define DIALOG_TRIGGERSSELECTAREACT	"Nombre de carrés devant être sélectionnés..."
#define DIALOG_TRIGGERSSELALLAREA	"Un joueur sélectionne toute la zone"
#define DIALOG_TRIGGERSSELALLAREATXT	"Joueur devant sélectionner la zone"
#define DIALOG_TRIGGERSCREATURELEVEL	"Niveau de la créature"
#define DIALOG_TRIGGERSCREATURELVLCNT	"Le niveau de la créature doit être..."
#define DIALOG_TRIGGERSREPEATTITLE	"Nombre d'utilisation du déclencheur"
#define DIALOG_TRIGGERSREPEATONETEXT	"Une seule fois"
#define DIALOG_TRIGGERSREPEATMORETEXT	"fois"
#define DIALOG_TRIGGERSREPEATINFTEXT	"Aucune limite"

#define DIALOG_ACTIONSTITLE		"Actions..."
#define DIALOG_ACTIONSTYPETITLE		"Sélectionnez le type d'action"
#define DIALOG_ACTIONSTYPELIST		"Liste des actions"
#define DIALOG_ACTIONSVARDST		"Variable cible"
#define DIALOG_ACTIONSVARSRC		"Variable source"
#define DIALOG_ACTIONSVARTITLE		"Modification d'une variable"
#define DIALOG_ACTIONSVARSET		"Placer"
#define DIALOG_ACTIONSVARADD		"Ajouter"
#define DIALOG_ACTIONSVARSUB		"Soustraire"
#define DIALOG_ACTIONSVARVARSET		"Placer la valeur de la variable source"
#define DIALOG_ACTIONSVARVARADD		"Ajouter la valeur de la variable source"
#define DIALOG_ACTIONSVARVARSUB		"Soustraire la valeur de la variable source"
#define DIALOG_ACTIONSTIMTITLE		"Activation d'un compteur"
#define DIALOG_ACTIONSCREATURETITLE	"Ajout d'une créature"
#define DIALOG_ACTIONSCREATURETYPE	"Créature à ajouter"
#define DIALOG_ACTIONSCREATURELEVEL	"Niveau"
#define DIALOG_ACTIONSCREATUREOWNER	"Joueur qui reçoit la créature"
#define DIALOG_ACTIONSCREATUREOPTIONS	"Options de la créature"
#define DIALOG_ACTIONSCREATUREX		"X:"
#define DIALOG_ACTIONSCREATUREY		"Y:"
#define DIALOG_ACTIONSCREATUREAREA	"Utiliser les positions de départ de la zone..."
#define DIALOG_ACTIONSELEM		"Ajout/Suppression d'un élément"
#define DIALOG_ACTIONSELEMLIST		"Liste des éléments"
#define DIALOG_ACTIONSELEMPLAYER	"Joueur concerné"
#define DIALOG_ACTIONSELEMADD		"Ajouter l'élément"
#define DIALOG_ACTIONSELEMSUB		"Supprimer l'élément"
#define DIALOG_ACTIONSSHOW		"Activer/Supprimer l'illumination d'une zone"
#define DIALOG_ACTIONSSHOWAREA		"Zone concernée"
#define DIALOG_ACTIONSSHOWDEACTIVATE	"Désactiver l'illumination"
#define DIALOG_ACTIONSSHOWACTIVATE	"Activer l'illumination"
#define DIALOG_ACTIONSVISIBLE		"Activer/Désactiver le brouillard de guerre"
#define DIALOG_ACTIONSVISIBLEAREA	"Zone concernée"
#define DIALOG_ACTIONSVISIBLESHOW	"Désactiver le brouillard de guerre"
#define DIALOG_ACTIONSVISIBLEHIDE	"Activer le brouillard de guerre"
#define DIALOG_ACTIONSBAND		"Libérer une bande de héros"
#define DIALOG_ACTIONSHEROSLIST		"Bande de héros à libérer"
#define DIALOG_ACTIONSBANDAREA		"Zone dans laquelle les héros doivent être libérés"
#define DIALOG_ACTIONSBANDINVASION	"Envahisseurs dans un p'tit donjon"
#define DIALOG_ACTIONSBANDRANDOM	"Définir aléatoirement le type des créatures"
#define DIALOG_ACTIONSGATE		"Destruction d'un portail de héros"
#define DIALOG_ACTIONSGATENAME		"Portail à détruire"
#define DIALOG_ACTIONSSQUARE		"Changer un carré de terrain"
#define DIALOG_ACTIONSSQUARESOFT	"Terrain de remplacement"
#define DIALOG_ACTIONSSQUAREOWNER	"Joueur détenant le nouveau terrain"
#define DIALOG_ACTIONSSQUARERECT	"Changer tout un rectangle"
#define DIALOG_ACTIONSSQUAREBRIDGES	"Note: les ponts sont placés sur de l'eau"
#define DIALOG_ACTIONSLIGHT		"Activer/Désactiver les étoiles/le clignotement sur un bouton"
#define DIALOG_ACTIONSLIGHTLIST		"Liste des boutons"
#define DIALOG_ACTIONSLIGHTSET		"Activer les étoiles/le clignotement"
#define DIALOG_ACTIONSLIGHTCLEAR	"Désactiver les étoiles/le clignotement"
#define DIALOG_ACTIONSLIGHTTIME		"Durée du clignotement"
#define DIALOG_ACTIONSSAY		"Dire quelque chose"
#define DIALOG_ACTIONSSAYNAME		"Identificateur de la voix"
#define DIALOG_ACTIONSSAYNOTEXT		"Ne pas afficher le texte correspondant"
#define DIALOG_ACTIONSVIEW		"Activer/Désactiver la vue cinématique"
#define DIALOG_ACTIONSVIEWSET		"Activer la vue cinématique"
#define DIALOG_ACTIONSVIEWCLEAR		"Désactiver la vue cinématique"
#define DIALOG_ACTIONSMOVECAMERA	"Déplacer la caméra au-dessus d'une zone"
#define DIALOG_ACTIONSMOVECAMERAAREA	"Zone cible"
#define DIALOG_ACTIONSROTATECAMERA	"Faire tourner la caméra au-dessus d'une zone"
#define DIALOG_ACTIONSROTATEANGLE	"Angle de rotation (en degrés)"
#define DIALOG_ACTIONSROTATEWAIT	"Durée (en secondes)"
#define DIALOG_ACTIONSROOM		"Afficher la prochaine salle"
#define DIALOG_ACTIONSROOMLIST		"Salle à afficher"
#define DIALOG_ACTIONSSLAPS		"Afficher le nombre de claques restantes"
#define DIALOG_ACTIONSSLAPSTEXT		"Nombre de claques (0 pour désactiver l'affichage)"
#define DIALOG_ACTIONSTIMER		"Afficher le temps restant"
#define DIALOG_ACTIONSTIMERTEXT		"Nombre de secondes"
#define DIALOG_ACTIONSTIMERDISABLE	"Un temps égal à 00:00:00 désactive l'affichage"
#define DIALOG_ACTIONSTARGET		"Désigner en tant que cible principale"
#define DIALOG_ACTIONSTARGETCLEAR	"Désactiver la désignation"
#define DIALOG_ACTIONSTARGETFIGHT	"Ennemi à abattre"
#define DIALOG_ACTIONSTARGETJAIL	"Ennemi à emprisonner"
#define DIALOG_ACTIONSTARGETTORTURE	"Ennemi à convertir"
#define DIALOG_ACTIONSPARAMS		"Modifier les paramètres de la créature"
#define DIALOG_ACTIONSPARAMSPLLIST	"Joueur cible"
#define DIALOG_ACTIONSPARAMSAREA	"Zone cible"
#define DIALOG_ACTIONSPARAMSROOMS	"La créature détruit les salles ennemies"
#define DIALOG_ACTIONSPARAMSWALLS	"La créature détruit les murs ennemis"
#define DIALOG_ACTIONSPARAMSGOLD	"La créature vol l'or ennemi"
#define DIALOG_ACTIONSPARAMSSPELLS	"La créature vol les sorts de l'ennemi"
#define DIALOG_ACTIONSPARAMSCRATES	"La créature vol les caisses ennemies"
#define DIALOG_ACTIONSPARAMSKILL	"La créature tue les créatures de l'ennemi"
#define DIALOG_ACTIONSPARAMSATTACK	"La créature attaque le joueur"
#define DIALOG_ACTIONSPARAMSSTAY	"La créature reste sur place"
#define DIALOG_ACTIONSPARAMSGO		"La créature tente de rejoindre la zone"
#define DIALOG_ACTIONSPARAMSJAIL	"La créature tente une évasion"
#define DIALOG_ACTIONSRUN		"Faire/Arrêter de faire courir la créature"
#define DIALOG_ACTIONSRUNSET		"Faire courir la créature"
#define DIALOG_ACTIONSRUNCLEAR		"Arrêter de faire courir la créature"
#define DIALOG_ACTIONSOWNER		"Changer le détenteur d'une salle"
#define DIALOG_ACTIONSOWNERLIST		"Nouveau joueur détenant la salle"
#define DIALOG_ACTIONSALLIES		"Etablir/rompre une alliance"
#define DIALOG_ACTIONSFIRSTALLIE	"Premier joueur concerné"
#define DIALOG_ACTIONSSECONDALLIE	"Deuxième joueur concerné"
#define DIALOG_ACTIONSSETALLIANCE	"Etablir une alliance"
#define DIALOG_ACTIONSCLEARALLIANCE	"Rompre une alliance"
#define DIALOG_ACTIONSGENERATE		"Faire sortir une créature d'un portail"
#define DIALOG_ACTIONSGENTYPE		"Créature à générer"
#define DIALOG_ACTIONSPORTALS		"Changer le statut des portails"
#define DIALOG_ACTIONSPORTALSOPENED	"Ouvrir les portails"
#define DIALOG_ACTIONSPORTALSCLOSED	"Fermer les portails"
#define DIALOG_ACTIONSMOODS		"Modifier l'humeur des créatures"
#define DIALOG_ACTIONSMOODSON		"Activer l'humeur des créatures"
#define DIALOG_ACTIONSMOODSOFF		"Désactiver l'humeur des créatures"
#define DIALOG_ACTIONSTIMERSPEECH	"Activer/désactiver le décompte vocal du temps restant"
#define DIALOG_ACTIONSTIMERSPEECHON	"Activer le décompte vocal"
#define DIALOG_ACTIONSTIMERSPEECHOFF	"Désactiver le décompte vocal"
#define DIALOG_ACTIONSCAMERAPATH	"Exécuter un mouvement de caméra prédéfini"
#define DIALOG_ACTIONSCAMERAPATHAREA	"Zone à partir de laquelle le mouvement se déclenche"
#define DIALOG_ACTIONSCAMERAPATHID	"Identificateur du mouvement"
#define DIALOG_ACTIONSCAMERAPATHCEON	"Afficher le plafond"
#define DIALOG_ACTIONSCAMERAPATHCEOFF	"Cacher le plafond"
#define DIALOG_ACTIONSSYSMSGS		"Activer/désactiver les messages du jeu"
#define DIALOG_ACTIONSSYSMSGSON		"Activer les messages"
#define DIALOG_ACTIONSSYSMSGSOFF	"Désactiver les messages"
#define DIALOG_ACTIONSMUSIC		"Niveau sonore de la musique"
#define DIALOG_ACTIONSMUSICSILENCE	"0"
#define DIALOG_ACTIONSMUSICFULLVOLUME	"100"
#define DIALOG_ACTIONSATTACK		"Modifier le comportement d'attaque de la créature"
#define DIALOG_ACTIONSATTACKON		"La créature attaque"
#define DIALOG_ACTIONSATTACKOFF		"La créature n'attaque pas"
#define DIALOG_ACTIONSSHOWHEALTH	"Afficher les pétales de la créature"
#define DIALOG_ACTIONSSHOWHEALTHTIME	"Durée d'affichage (en secondes)"
#define DIALOG_ACTIONSFXTITLE		"Activer/Désactiver un effet"
#define DIALOG_ACTIONSFXTOGGLE		"Effet concerné"
#define DIALOG_ACTIONSFXENABLE		"Activer l'effet"
#define DIALOG_ACTIONSFXDISABLE		"Désactiver l'effet"

/*** Textes des menus ************************************************************/

#define DIALOG_MENUFILE			"Fichier"
#define DIALOG_MENUEDIT			"Edition"
#define DIALOG_MENUPAINT		"Dessin"
#define DIALOG_MENUDISPLAY		"Afficher"
#define DIALOG_MENUPROPERTIES		"Propriétés"
#define DIALOG_MENUHELP			"Aide"

/*** Textes des boîtes de dialogues (chemins de camera) **************************/

#define DIALOG_PATHSTITLE		"Chemins de caméra répertoriés"
#define DIALOG_PATHSIDENTIFIERS		"Identificateurs"
#define DIALOG_PATHSINFO		"Description de l'identificateur sélectionné"

/*** Textes divers ***************************************************************/

#define DIALOG_COPYRIGHT		"Créateur de carte pour Dungeon Keeper II®\0"
#define DIALOG_PATHSDESCRIPTION		"Description des chemins de caméra\0"
